### ISSUE TITLE
Modify NPC random spawn logic

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#114]
NPCs should not randomly spawn:

- [ ] Within 64 blocks of a player
- [ ] Within 32 blocks of a tile entity
- [ ] Within 64 blocks of the world spawn location
- [ ] On protected worlds
- [ ] Within 64 blocks of the **receiving** stargate on a world  
- [ ] Within 128 blocks of another NPC of the same type (Bosses only)
- [ ] Within 32 blocks of another NPC of a faction that is hostile to the one of the spawning NPC

**Comment by Joey4213** [comment]
Sounds good. :D

**Comment by thestargateman** [comment]
Perfect. 👍 

Maybe in the future there can be a mechanic to claim a world to prevent hostile spawns? Currently more of an annoyance than a cool feature. It certainly is cool to watch them fight but would prefer to do that in dedicated quests / missions than getting one shot by a First Prime. - MCRocker47

**Comment by StargateMC** [comment]
@thestargateman Yes Claims will prevent it when i implement them.... and some worlds will be claimed by NPC factions so that npcs hostile to them do not spawn (or as often).
