### ISSUE TITLE
SGCraft requires an update to fix a bug that prevents computer dialling

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#115]
Function `dial("P2X3-YZ0-PL")` is not working. It returns a nil.

**Comment by RedstoneSucht** [comment]
![grafik](https://user-images.githubusercontent.com/35812887/80747057-1b846880-8b23-11ea-931a-92036aeade11.png)

**Comment by StargateMC** [comment]
This should be resolved with the SGCraft update coming as soon as I can find the time to sort it. Its about 4 hrs work.

**Comment by Joey4213** [comment]
coolio
