### ISSUE TITLE
Can't craft metal tail

### ISSUE THREAD

**Issue by ComputerCraft32** [StargateMC/IssueTracker#120]
The metal tail from Flan's mod has exactly the same recipe as the vanilla iron trapdoor, causing the latter to override and thus making it impossible to create most of the vehicles. The conflicting recipe is shapeless and consists of 4 iron ingots arranged in a 2*2 square.

**Comment by Joey4213** [comment]
I will fix in the next update. Thanks you :P

**Comment by StargateMC** [comment]
@Joey4213 need a recipe... upload it here.

**Comment by Joey4213** [comment]
[Prismarine.zip](https://github.com/StargateMC/IssueTracker/files/4604183/Prismarine.zip)

mk welp that should have the zs file in it for the crafting among other things is the metal tail fix

**Comment by Joey4213** [comment]
Ok @ComputerCraft32 your metal tail fix has been pushed, it was pushed quite a while ago and it just skipped over my mind so this matter is essentially closed.
Thanks for informing us and allowing us to fix it. :D

**Comment by Joey4213** [comment]
Fixed and needs closing @StargateMC
