### ISSUE TITLE
Recipe error on IC2 Stargate Power Unit

### ISSUE THREAD

**Issue by progmanpaul** [StargateMC/IssueTracker#123]
IC2 Stargate Power Unit isn't recognizing the Copper Plate item added by Ic2c Extras. The Copper Plate appears as the Magenta/Black 2x2 pattern. When you mouse over it the hover UI says, "No Use Item. IC2Exp Compat - Industrial Craft Classic".

**Comment by Joey4213** [comment]
I am able to correctly create this block, and it also does not require a a copper plate, you may have been trying to use to old recipe which no longer works I suggest installing JEI for the modpack as it will show you all the current recipes.
