### ISSUE TITLE
AR Atmospheric Terra former does not correctly operate

### ISSUE THREAD

**Issue by Joey4213** [StargateMC/IssueTracker#126]
The Advanced Rocketry atmospheric terraformer does not link to the biome changer remote when put into the machine

**Comment by DEVensiv** [comment]
That is a bug in the mod itself that exists in it by default

**Comment by Joey4213** [comment]
yes but from my understanding it should have been patched

**Comment by StargateMC** [comment]
@Joey4213 When was it patched? I may need to import the fix.

**Comment by Joey4213** [comment]
I believe it was patched in version 1.12.2-1.7.0-209
