### ISSUE TITLE
When you die on a space station you cannot respawn...

### ISSUE THREAD

**Issue by thestargateman** [StargateMC/IssueTracker#127]
Has happened to Joey, Jay and now me (MCRocker47). When one dies on a space station they cannot join back into the game without having their player data reset.

**Comment by StargateMC** [comment]
Please clarify how you died.

**Comment by Joey4213** [comment]
incorrect, i died on my station a few times and was able to join back, i vividly remember killing myself on a station by dying with no air

**Comment by thestargateman** [comment]
i died of fall damage

**Comment by thestargateman** [comment]
can now respawn, but on earth's surface. Am very stuck.

**Comment by StargateMC** [comment]
OK i need to do some testing here.  Once I can reproduce ill fix.

**Comment by thestargateman** [comment]
thanks :)

**Comment by Octanne** [comment]
Two of my friend : cauchemart & JanerV2 had the same bug, when you die in space you time out and every time you try to reconnect You can rejoin only after the server reboot.

**Comment by Joey4213** [comment]
I have seen that AR deems some deaths "acceptable" in a certain sense, if you suffocate to death in space you respawn as you should, but if you die by say a stargate vortex then your playerdata gets corrupted (true by the way so be careful).

**Comment by Joey4213** [comment]
@StargateMC this seems to have been fixed in the recent AR update, so for now I believe this matter should be closed until it happens again, but I can confirm from first hand experience that my playdata was fine after dying numerous times on a space station in a method that previously caused the data to require a reset.

**Comment by StargateMC** [comment]
Fantastic news!
