### ISSUE TITLE
if a stargate is moved, it no longer instant locks chevrons

### ISSUE THREAD

**Issue by thestargateman** [StargateMC/IssueTracker#130]
self explained... even if u have a dhd if u move the stargate it no longer instantly locks chevrons instead dialling like the SGC gate...

**Comment by Joey4213** [comment]
that is a feature meant to happen

**Comment by Joey4213** [comment]
the instant lock is from a previous update and we decided we liked it better with the rotation of the symbol wheel so that is suppose to happen and in fact the instant lock is not suppose to happen

therefore this post is now irrelevant

**Comment by thestargateman** [comment]
it just makes the gates annoying to use... i vote for a bysopoll bot or whatever he calls them unless there already was one... if there was... why?

**Comment by Joey4213** [comment]
we just decided and he was all for wanting the gate change back to rotating so it was his decision and you just gotta deal with it everyone else is fine with it.. jsut dont break an instadial gate

**Comment by StargateMC** [comment]
The reason it was enabled was because I made a config change we then backed out of.
When you moved the gate it triggered a configuration reset to the baseline.

Sorry we're not going to allow instantly locking as it makes it too easy to keep a gate busy 100% of the time.
