### ISSUE TITLE
Suggestion to use High Quality textures for SGCraft

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#133]
So, i've found some textures on my harddrive that are made for SGCraft and provide a much higher Quality. I suggest the replacement of the current ones with these. Pictures showing the Textures in Action are attached as well.
[textures.zip](https://github.com/StargateMC/IssueTracker/files/4612920/textures.zip)
![2020-04-29 (4)](https://user-images.githubusercontent.com/49319803/81629301-18cb2280-9403-11ea-9067-7afffe64cd6d.png)
![2020-04-29 (6)](https://user-images.githubusercontent.com/49319803/81629305-1bc61300-9403-11ea-902e-a8ab37cb0e78.png)
![2020-04-29 (7)](https://user-images.githubusercontent.com/49319803/81629307-1e286d00-9403-11ea-9188-a0bc8e537ebf.png)
![2020-04-29 (2)](https://user-images.githubusercontent.com/49319803/81629310-22548a80-9403-11ea-84db-dc782ebe4cdd.png)

![2020-04-29 (3)](https://user-images.githubusercontent.com/49319803/81629429-68115300-9403-11ea-8a08-ff94226567d5.png)
![2020-04-29 (5)](https://user-images.githubusercontent.com/49319803/81629471-7cede680-9403-11ea-9d0d-3eb431fa9dc7.png)
![2020-04-29 (9)](https://user-images.githubusercontent.com/49319803/81629477-7fe8d700-9403-11ea-897e-39a290928b26.png)

**Comment by ComputerCraft32** [comment]
Wow, look nice!

**Comment by StargateMC** [comment]
Definitely keen on adding. Thanks!
Do you know the author of them? Need that for the credit section of the site im working on.

**Comment by SunnyM00n** [comment]
The Author was OrganicHoney

**Comment by StargateMC** [comment]
This will be part of the next update.
