### ISSUE TITLE
Allowing to dial out of someone is trying to dial in

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#139]
I ask if it’s possible to enable the dialing out while someone is trying to dial in. Yes, this is canon, the gates operate with “first dials completely, first gets wormhole

**Comment by StargateMC** [comment]
Sorry, but this isnt going to be something I can justify.

Players would simply dial out as fast as they can to stop a hostile incoming dial.... instead of using an iris.
