### ISSUE TITLE
No mobs spawn on my planet

### ISSUE THREAD

**Issue by FoosterKing** [StargateMC/IssueTracker#146]
No mobs except for custom npcs spawn. all my farm animals have been despawned and no hostile mobs spawn

**Comment by StargateMC** [comment]
Can you confirm if there are freshly spawned npcs on your world?  Or are they ones that spawned in the past few days?

**Comment by FoosterKing** [comment]
No NPC's spawn now. No mobs spawn now. I needed spider eyes, was told to hunt for them but now I can't get any.

**Comment by Joey4213** [comment]
i can confirm that npc's spawn in general though if that helps at all

**Comment by StargateMC** [comment]
Ill add a spider mob today sometime.

**Comment by StargateMC** [comment]
Mobs will be added over time. Submit a request for a mob and why you would like to see it.

eg: A Bird type NPC so it can drop feathers.
