### ISSUE TITLE
Cant Scroll or navigate to other galaxies in the planet selector

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#147]
If you want to select a system(Pic) you can't scroll down
![grafik](https://user-images.githubusercontent.com/35812887/82155020-4506f900-9872-11ea-9e37-c9d9f81cc793.png)

**Comment by StargateMC** [comment]
OK, looking into it.

**Comment by StargateMC** [comment]
@zmaster587 Sorry for the ping, but do you have any idea what can be causing this? 
We have 25,000 dimensions, but outside of expanding the maximum dimension count in our build of AR I haven't changed anything.

Any chance you can point me in the right direction as to why this wont scroll? 
Aka. Likely a problem in X.java near Y sorta thing...

**Comment by Nerion1** [comment]
This has been fixed.
