### ISSUE TITLE
Add Universe Stargate Type (Textures and sounds attached)

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#151]
I am proud to announce the publishing of my Destiny Resource Pack. This Pack replaces Sounds and Textures of the Milkyway Gate ATM. This Pack does not come with special PDD Textures, because i couldn't figure out how to create those. This pack does not have special DHD textures, because Destiny Gates don't have a DHD. Some screenshots showcasing the pack are Attached:

![2020-05-22 (3)](https://user-images.githubusercontent.com/49319803/82692896-cf7b9e00-9c60-11ea-8663-a156156c86a8.png)
![2020-05-22 (2)](https://user-images.githubusercontent.com/49319803/82692901-d0accb00-9c60-11ea-839c-9cb97e9fbe1a.png)
![2020-05-22 (1)](https://user-images.githubusercontent.com/49319803/82692903-d1ddf800-9c60-11ea-98ae-84fa769c3177.png)

Credit goes to Carter's Addon Pack for Sounds and Textures
https://github.com/RafaelDeJongh/cap_resources

[Destiny Master.zip](https://github.com/StargateMC/IssueTracker/files/4669437/Destiny.Master.zip)

**Comment by StargateMC** [comment]
Wooop!! Thanks mate! We will get this in ASAP.

**Comment by StargateMC** [comment]
@SunnyM00n The Zip you've attached contains standard milkyway textures?

**Comment by Joey4213** [comment]
@StargateMC I would wait for the version 1.1 that will be out in a day or two it fixes a texture and allows correct sounds

**Comment by JayCoolGuy** [comment]
Here it is Sokar..
[Destiny.Master.zip](https://github.com/StargateMC/IssueTracker/files/4671336/Destiny.Master.zip)

**Comment by StargateMC** [comment]
@Joey4213 @SunnyM00n When is this going to be ready ? :)

**Comment by SunnyM00n** [comment]
There are 2 versions: One with the starting sound used for the dhd and one version where it is the first chevron. The problem is, that the mod apparently chooses the chevron sounds randomly, so that would have to be fixed. The texture that's supposed to be fixed is the wormhole texture that is currently shared by all stargates, that would need a change too. I'm now repacking the textures and will add them here in a few mins

**Comment by SunnyM00n** [comment]
This is the version with the sounds placed as intended 
[sgcraft-sounds original.zip]
(https://github.com/StargateMC/IssueTracker/files/4690205/sgcraft-sounds.original.zip)

This is the version with the start sound for the dhd
[sgcraft- sounds tweaked to fit usage.zip](https://github.com/StargateMC/IssueTracker/files/4690218/sgcraft-.sounds.tweaked.to.fit.usage.zip)

**Comment by SunnyM00n** [comment]
Oh, and i adjusted the file structure to fit the usage by the mod if that gate will be native
