### ISSUE TITLE
Ensure terraforming doesnt bypass protection and enable it

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#153]
Disabled in AR config line 126:

# EXPERIMENTAL: If set to true allows contruction and usage of the terraformer.  This is known to cause strange world generation after successful terraform
    B:allowTerraforming=false

**Comment by Joey4213** [comment]
see but the reason i didnt think that was it was because we were able to construct it... i mean i dont want to rule out anything so @StargateMC can you take a lookse?

**Comment by RedstoneSucht** [comment]
i think you can always build it. but when i tried to turn it on, it turned off intant

**Comment by StargateMC** [comment]
Once I disable it in protected areas/worlds I will enable.

**Comment by RedstoneSucht** [comment]
ok

**Comment by Joey4213** [comment]
#126 bump

**Comment by StargateMC** [comment]
True or false: Terraforming is not possible unless you can place a block in a world?

**Comment by Joey4213** [comment]
i dont understand the question

**Comment by Joey4213** [comment]
you need to build the terraformer if thats what your asking

**Comment by StargateMC** [comment]
@Joey4213 So it cant be placed on a protected world? It doesn't work from orbit?

**Comment by TheRedCreations** [comment]
It only works on the planet where the terraformer stays. In Space it won't work.
