### ISSUE TITLE
UU Matter replicator balancing

### ISSUE THREAD

**Issue by FoosterKing** [StargateMC/IssueTracker#158]
Some items have a UU matter requirement higher than the replicator limit. A diamond costs 24.1mB to make, whereas a spider eye costs 54.32 B which is triple the limit of the replicator. Can we reduce the UU requirement of the Spider eyes and allow ink sacks to be replicated

**Comment by Joey4213** [comment]
I can look into editing the config for the replicator and giving it to sokar, if I do it, it will be pushed when the MFFS is pushed so in about a week im hoping

**Comment by FoosterKing** [comment]
Epic Joey thanks

**Comment by RedstoneSucht** [comment]
[ink.zip](https://github.com/StargateMC/IssueTracker/files/4705880/ink.zip)
Recipe for ink sac. crafted by 4 coal dust

**Comment by Joey4213** [comment]
I made a more logical recipe and am now working on finishing the MFFS recipes and once that is done I will be looking into the UU matter bs :P
Best Regards 
Joey
