### ISSUE TITLE
When you die you die.

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#159]
When you die, you die,

Upon player death, a player gets respawned on a habitable planet, however, they take anywhere from 1-10 hearts of damage, killing or maiming them. Upon death, it is said to be suffocation damage.

**Comment by Joey4213** [comment]
So what you mean is that when you respawn the server says you've suffocated but you havent?

**Comment by BenFRC5147** [comment]
yes

**Comment by StargateMC** [comment]
Unable to reproduce this as yet. Please provide detailed instructions (where and when you died for one) before reopening.
