### ISSUE TITLE
crafting recepie for ender lillies

### ISSUE THREAD

**Issue by Luckyradkid1** [StargateMC/IssueTracker#162]
i'd like there to be a crafting recipe for ender lillies to get black dye. i need black dye but there isnt any way atm.
please dont use black dye in the recipe, the reason i need it is for black dye.

**Comment by Joey4213** [comment]
i already have a crafting recipe for black dye/ink sacks if you look at the other post about it, it will get pushed sokar said this weekend its up to him this is closed
