### ISSUE TITLE
Remove weakness effect from wolves

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#163]
Wolves are really overpowered, they hit you for a relatively small amount of damage, but they can hit fast, and also, when they hit you, they give you a weakness effect that lasts for about 5-10 seconds that literally makes it impossible to hit them.

Also they spawn in weird places like inside of built structures

**Comment by StargateMC** [comment]
If we simply removed the weakness effect, would that suffice?

**Comment by draksterau** [comment]
This has been done. All future spawning wolves have no weakness effect and do reduced damage.
