### ISSUE TITLE
Improvements to NPC Spawn logic

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#164]
I'd suggest the following changes to spawn logic:

- [ ] Only allowing NPCs to spawn within 25 blocks of sea level on a world, and only when there is nothing above them.

This will prevent NPCs spawning inside buildings, under trees or in caves and provide guarrranteed safe areas - eg: high in the mountains or underground

Vote with a 👍  or 👎  emoji. Comment below for more suggestions

**Comment by Nerion1** [comment]
NPC's being revamped, will consider upon implementation.
Closed.
