### ISSUE TITLE
Add an NPC mob that drops feathers

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#165]
Can we please get a recipe for feathers or a change to the Engineering press recipe which stops it requireing the name plate press, because the name plate press is really dumb and unused anyway.

regardless, the Name Plate Press needs Feathers to make the nametag component, and feathers are unobtainable afaik

**Comment by Joey4213** [comment]
actually i made it possible to be made, they are made to be fairly difficult, and feathers are obtainable, get scrap boxes and you have a chance for feathers :D
Have good day

**Comment by BenFRC5147** [comment]
Requiring the random chance of scrap boxes to get feathers is stupid. Name Presses are useless and have no purpose being in the recipe for the Engineering press.

**Comment by Joey4213** [comment]
then dont make it, everyone else has been fine with it...

**Comment by BenFRC5147** [comment]
It's required for the Engineering press, which is a useful item. The Name Press is not used for anything else. I can't speak for anyone else.

**Comment by Joey4213** [comment]
either way i was told to make them obtainable but not super easy so i did that

**Comment by BenFRC5147** [comment]
Okay, but there are numerous other ways to make them hard to obtain, in fact, they already are with the iridium plates. There are no mobs on planets which drop feathers, as such making it nearly impossible to obtain the most basic useless press

**Comment by Joey4213** [comment]
At the time i made them chickens existed you want me to change it? because if i do it will be more fun
and you will need to wait a week for it to get pushed

**Comment by BenFRC5147** [comment]
I mean a week is probably sooner than I'll get it with the recyclers.

**Comment by Joey4213** [comment]
not true for one, and two you left out the part where it would be more fun....

**Comment by BenFRC5147** [comment]
It would be more fun to what? sit in my base waiting on my recyler to spit out 9 scraps, make those scraps into a scrap box and open it for my 1.94% chance at one feather?

**Comment by Joey4213** [comment]
yes...

**Comment by BenFRC5147** [comment]
That is not fun.

**Comment by StargateMC** [comment]
Couldn't we just make a birdlike NPC mob?
