### ISSUE TITLE
Add Votifier mod

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#169]
Add votifier mod to support  Naquadah rewards  being paid for votes each day.

I need help as I cant get the mod working.... anyone want to give it a try?

https://www.curseforge.com/minecraft/mc-mods/voting

**Comment by BenFRC5147** [comment]
Have you already put it into test/live and gotten the key from the file path it tells you to?

What point are you having a problem with. Nobody can really test it themselves without their own server/votifier approved website

**Comment by BenFRC5147** [comment]
After you've gotten the mod into one of the servers and then run the server once with it it should generate that file, and then you have to edit the listing on Minecraftservers.org to include your public key, port, and votifier ip

**Comment by draksterau** [comment]
This has been pushed ahead of schedule! Please let me know if you have any issues.
