### ISSUE TITLE
Openturrets don't target CustomNPCs

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#173]
Openturrets does not seem to target CustomNPC wolves, even with the attack neutrals box ticked. No other NPCs spawn on my world to try it on but I feel it'd have similar results.

**Comment by StargateMC** [comment]
I should be able to use the owner of the OMT turret to determine your reputation and therefore what the turret should shoot automatically.

Leave it with me.

**Comment by draksterau** [comment]
OK the plan is:

- [ ] Have Turrets target hostile NPCs when you enable Mob targeting
- [ ] Have Turrets target neutral NPCs when you enable Neutral targeting
- [ ] Turrets that fire on NPCs and kill them will affect the turret owner's reputation
- [ ] NPCs which get fired on by a turret will retaliate against turrets
