### ISSUE TITLE
Add recipee for using ic2 scrapboxes

### ISSUE THREAD

**Issue by nosknut** [StargateMC/IssueTracker#179]
With the removal of atonomous activators there is no way to use scrapboxes on a large scale. I propose a recipe, be it crafting or a machine processing that lets you unpack them.

**Comment by TheRedCreations** [comment]
use a Dispenser to open the boxes

**Comment by Joey4213** [comment]
I would make a recipe but I cannot create one to allow the unpacking of the scrap boxes it would only allow for the output of 1 item type

**Comment by nosknut** [comment]
I will test the dispenser idea

**Comment by Joey4213** [comment]
i assume this is essentially closed?
