### ISSUE TITLE
Consider disabling ae2 channels

### ISSUE THREAD

**Issue by nosknut** [StargateMC/IssueTracker#180]
This issue could probably be set on hold for a while until i collect some more information.

I have observed some glitches in ae2 related to components of the network occasionally disappearing as well as some recipes disapperaring from the system at times. Also some glitches related to the autocrafting system and terminals not being able to detect items in the network. This may or may not be related to bugs with channels and/or 2p2 tunnels. If that is the case, disabling channels might fix the problem. Channels are a boolean in the ae2 config.

**Comment by BenFRC5147** [comment]
Also, to be fair, channels are a fairly pointless limitation anyway, the max #of channels is somewhere in the hundreds of thousands at the low end. I have also noticed some bugginess with them in 1.12

**Comment by nosknut** [comment]
They do add elements to the game and there is a certain elegance to the concept but i think they might be doing more harm than good right now. And they dont realy add much of a challenge if you remain organized. They might even be a performance hog if looped and that can very easily happen

**Comment by draksterau** [comment]
Is this related to #175 ?

**Comment by draksterau** [comment]
@nosknut can you test in SP? Or want me to push the disable to test?

**Comment by nosknut** [comment]
It's too unpredictable to reliably test. Atm it is fine its not extremely breaking or anything its just confusing and weird so disabling channels just for this alone isnt a good idea. But if we do decide that channels arent worth having enabled at all it might fix it, So i would rather ask the question do channels add anything to the game and not will channels fix the issue because i havent spent enough time debugging this to say anything for sure. Its just a hunch atm

**Comment by nosknut** [comment]
> Is this related to #175 ?

I am pretty sure it has nothing to do with it.
