### ISSUE TITLE
MFFS crafting recipe update missing a needed crafting recipe.

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#181]
Force Power crystals still do not have a crafting recipe yet.  Those are a necessary part of MFFS progression as they are used in a few other required crafting recipes in the mod.  
![Screenshot (348)](https://user-images.githubusercontent.com/65046207/84195835-11c02000-aa54-11ea-9f81-6fa800ddb5c8.png)
![Screenshot (349)](https://user-images.githubusercontent.com/65046207/84195838-12f14d00-aa54-11ea-940a-32edf8579bfa.png)
![Screenshot (344)](https://user-images.githubusercontent.com/65046207/84195839-12f14d00-aa54-11ea-96fe-288fe4d292d4.png)
![Screenshot (346)](https://user-images.githubusercontent.com/65046207/84195840-1389e380-aa54-11ea-927e-c9e1497918ce.png)
![Screenshot (347)](https://user-images.githubusercontent.com/65046207/84195842-14227a00-aa54-11ea-803e-d6786136c991.png)

**Comment by JayCoolGuy** [comment]
Also the MFFS cards, and multi tools don’t have crafting recipes

**Comment by Joey4213** [comment]
@JayCoolGuy look at the wiki, i didnt add them bc they are craftable it just dosent show for some reason

**Comment by JayCoolGuy** [comment]
O ok I’ll check it out
