### ISSUE TITLE
(Minor) Crash after high-rubberbanding period

### ISSUE THREAD

**Issue by nosknut** [StargateMC/IssueTracker#188]
[crash-2020-06-12_01.22.52-client.txt](https://github.com/StargateMC/IssueTracker/files/4767769/crash-2020-06-12_01.22.52-client.txt)
I was heavily rubberbanding for a while. The latency was good because some blocks could be broken very easily while 5 blocks were not so esily broken and kept popping back without dropping when i mined them. I doubt this will happen often but it might be worth looking in to

**Comment by draksterau** [comment]
@nosknut this is an unavoidable crash - RandomPatches is currently extending the timeout for connections to well beyond what Forge and Minecraft normally have to facilitate people with a dodgy connection to the server - this is not your fault, we're on cheap hosting.

If i remove it, we'll need to upgrade hosting to OVH ($100+USD/mo) to minimise timeout errors.
