### ISSUE TITLE
Request - Ingame chat channels

### ISSUE THREAD

**Issue by Tappentine** [StargateMC/IssueTracker#189]
Not sure if this could be implemented but here is an idea for communication.

We should change the server to communicate locally rather than as per the server. For example
- if you are on a planet, this is local to the planet, you can talk to everyone
-On another planet, you must dial to them to talk or find another way, I.E. Opencomputers
- If you are in orbit of a planet, if you have a communicator device, you can talk planets ide (might be good in a war scenario to address the full planet)

In terms of discord, discord messages are still broadcast to everyone.

Potentially this could be used to get people to search more using ships and Stargates, allowing alliances to be formed or enemies.

An example scenario, Planet A has a base, suddenly they hear a war threat in orbit, Planet B is attacking. Planet A either goes to their sub space communicator to call for help (oh no, this is jammed) so they go to the Stargate to dial to send messages for the other side to hear. Planet C heard the call for help and warps over as quick as they can. Planet A sends out a planet broadcast suggesting to evacuate

**Comment by ComputerCraft32** [comment]
This sounds good, but can't this all be quickly overcome with discord? One can simply DM their ally for help, or DM their faction members for support?

**Comment by Tappentine** [comment]
True, but its good to have an in-game option for those who don't want to use discord

**Comment by ComputerCraft32** [comment]
It's putting them at a disadvantage though due to communication times.

**Comment by Tappentine** [comment]
This is primarily a lore friendly gameplay mechanic once the server has finished with more important bug fixes and updates

**Comment by ComputerCraft32** [comment]
I agree, this would be super awesome

**Comment by draksterau** [comment]
How about you guys find us a decent channel chat forge mod then :)

**Comment by Tappentine** [comment]
I would, but this was more of an idea than a way of implementing, If it's something that interests the mod integrators, they will hopefully look into it

**Comment by Luckyradkid1** [comment]
this would be really cool, great idea

**Comment by ComputerCraft32** [comment]
Definitely after the more important issues are resolved, though

**Comment by Joey4213** [comment]
Done :D
