### ISSUE TITLE
Universe gates dial too fast

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#192]
Presently Universe gates have a dial speed of 8, compared to Pegasus 6 and MilkyWay 2.

This needs to be changed to 1.... in line with Canon.

- [ ] Update MilkyWay and Pegasus upgrade item tooltips
- [ ] Update sgcraft.cfg to reflect a default spin speed of 1.
- [ ] Update SGBaseTE to reflect a default spin speed of 1.
- [ ] Update StructureHandler to set spin speed to 1 for Universe gates.

**Comment by Joey4213** [comment]
1-4 are done :D
