### ISSUE TITLE
SGU Gates do not have a GDO texture set

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#193]
When opening the GDO Gui, both Pegasus and MilkyWay gates have a unique texture set, for both without iris, with iris, active, inactive etc.

SGU gates presently utilise the milkyway textures

**Comment by SunnyM00n** [comment]
[Universe GDO Textures.zip](https://github.com/StargateMC/IssueTracker/files/4793119/Universe.GDO.Textures.zip)

**Comment by SunnyM00n** [comment]
[Universe GDO.zip](https://github.com/StargateMC/IssueTracker/files/4793658/Universe.GDO.zip)

**Comment by draksterau** [comment]
Finally actioned :)
