### ISSUE TITLE
new OC dialer issue

### ISSUE THREAD

**Issue by Luckyradkid1** [StargateMC/IssueTracker#196]
the autoclose feature does not work

**Comment by draksterau** [comment]
Bit light on detail. But we got there.

**Comment by Luckyradkid1** [comment]
not sure what else to say xD

**Comment by TheRedCreations** [comment]
autoclose is working for sunny and me. but i'm not able to open the iris. the program closes the iris again.

**Comment by Joey4213** [comment]
yea, thats because the program isnt integrated with the stargate iris, it keeps closing it while you are opening it.

**Comment by Joey4213** [comment]
From what I have seen the auto close feature works fine, just need to make sure you have configured everything right, I will be closing this now
