### ISSUE TITLE
NBT data overflow through Mek Cardboard boxes

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#200]
[2020-06-15-3.log](https://github.com/StargateMC/IssueTracker/files/4777697/2020-06-15-3.log)

**Comment by draksterau** [comment]
# Use this file to tell Mekanism which blocks should not be picked up by a cardboard box.

# Proper syntax is "NAME META". Example (for stone):

# minecraft:stone 0

What items did you put in it?

**Comment by SunnyM00n** [comment]
ME Drives

**Comment by Joey4213** [comment]
i would like to add, that it is not unnatural for this to happen with what sunny did :D
