### ISSUE TITLE
Add a 'galaxy' level to the planet selectors

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#202]
Not sure how to do it yet, but I need to list it or people will keep asking for one.

**Comment by Luckyradkid1** [comment]
definetly this would be great

**Comment by BenFRC5147** [comment]
I was looking at the class for the holo selector, and while i have barely a clue how to create a new level, I did notice that the scale could probably be very easily changed, a potential dirty solution may be to just allow the scale to go even smaller than it currently goes to.

**Comment by Luckyradkid1** [comment]
but it would be hard to select the stars that are close together, and also the very tiny ones
