### ISSUE TITLE
Add the Destiny as an AR ship

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#205]
Destiny should be added with;

- [ ] Scripted jumps around the 1D Galaxy, with 5 minutes of down time between each that the ship is reachable by stargate
- [ ] A Random Dialler NPC that only dials nearby worlds, not a random world in the whole galaxy
- [ ] Destiny's stargate should always retain the same address

**Comment by TheRedCreations** [comment]
for point 3: DEST-INY-1D
