### ISSUE TITLE
Gate crafting to expensive

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#211]
Noone wants to craft a Gate with those recipes. The Users are going to steal the gates from other planets. PLEASE FIX THAT!

I show now a complete Recipe way for 1 ring block:
![grafik](https://user-images.githubusercontent.com/35812887/84776340-7a714480-afe0-11ea-9a7f-26a1bf029c34.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776476-a1c81180-afe0-11ea-9eed-eb628402eebd.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776485-a55b9880-afe0-11ea-8f03-26c9bc9d2bdc.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776561-bdcbb300-afe0-11ea-9bd2-8a5611071314.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776567-c0c6a380-afe0-11ea-8136-a7671a4f9a01.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776607-cd4afc00-afe0-11ea-997f-5a6c391cd4f9.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776640-db008180-afe0-11ea-82b7-42aec077205e.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776817-18650f00-afe1-11ea-9c77-7487788a08e2.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776830-1e5af000-afe1-11ea-8b30-8688552ba7f6.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776846-231fa400-afe1-11ea-871d-a1757bb228c7.png)
![grafik](https://user-images.githubusercontent.com/35812887/84776854-2581fe00-afe1-11ea-8760-fd278a8e3750.png)
Have fun with gates which get stolen!

**Comment by Joey4213** [comment]
this is a very similar recipe to the one used in 1.7.10, i am only trying to keep it both on what was there and to keep things a bit cannon, so if you want cannon i can remove the ability to obtain them any way other then stealing them

**Comment by TheRedCreations** [comment]
Tell me, who wants to craft a gate that is that expensive?

**Comment by Joey4213** [comment]
i do

**Comment by TheRedCreations** [comment]
except ypu

**Comment by Joey4213** [comment]
anyone that is desperate for a gate

**Comment by Joey4213** [comment]
ok how about this, i replicate the 1.7 recipes? it makes them very similar if not involving more work

**Comment by Joey4213** [comment]
Stargate base

Naquadah block | Quantum Core | Naquadah block
Quantum Core | Energy Crystal Four | Quantum Core
Naquadah Block | Quantum Core| Naquadah Block

Energy Crystal Four

	glass | naquadah | glass
	EnergyCrystalThree | naquadah | EnergyCrystalThree
	glass | glass | glass

Energy Crystal Three

	glass | naquadah | glass
	EnergyCrystalTwo | naquadah | EnergyCrystalTwo
	glass | glass | glass

Energy Crystal Two

	glass | naquadah | glass
	EnergyCrystalOne | naquadah | EnergyCrystalOne
	glass | glass | glass

Energy Crystal One

	glass | dye:14 | glass
	Glass | naquadah | glass
	glass | naquadah | glass

**Comment by Joey4213** [comment]
should i continue?

**Comment by SunnyM00n** [comment]
> The Users are going to steal the gates from other planets.

@Joey4213

**Comment by TheRedCreations** [comment]
ok. when someone destroys a users base and the user needs a gate, he don't want to build it

**Comment by Joey4213** [comment]
im telling you things, and asking you questions and you didnt answer any of it...

and i made multiple of the 1.7 gates when i needed to

**Comment by Joey4213** [comment]
it was my no means easy but it was in a certain sense fun, thats kinda the point tho... you dont want gates to be easy to make

**Comment by Joey4213** [comment]
and as for users stealing gates from other plants, well those gates will eventually get back there when someone needs to get off said planet

**Comment by SunnyM00n** [comment]
Or never...

**Comment by Joey4213** [comment]
ok well we can keep these recipes or we can take the ones from 1.7 that require even more quantum cores

**Comment by SunnyM00n** [comment]
What about reversing to the ones we had prior to the last recipe update?

**Comment by draksterau** [comment]
@SunnyM00n they were too easy before. Perhaps we need to dial them back a bit now though.

**Comment by Joey4213** [comment]
i made it more fair in #232
