### ISSUE TITLE
Request - Sync Mod

### ISSUE THREAD

**Issue by Tappentine** [StargateMC/IssueTracker#216]
## What is your suggestion?
We consider adding the Sync mod to the Stargate Modpack

>Why is this important?
Cloning is apart of the Stargate universe, with the Asgard doing it and it being a vital part to many of the plotlines

## How will this benefit players?
Sync works to create a shell which a player can control if he either dies, or if he switches to this using a Sync pod. Until then, the body stays in the pod waiting. This would benefit players who leave their planet and die, and get taken back to the nearest safe planet or just a different planet then they wanted, if they had the technology, they could go straight back home (when you spawn in a clone, you have none of your inventory) and then go find your stuff.

## How will this change for players?
I don't believe they'll be any issues, when ive used this mod in the past, it made it helpful to get back to home base upon death. Players will be able to know for sure that if a wolf kills them, they will go back to their home spot.

>Why is this important?
This is important as it gives players a chance to not have to try and dial back home after death, it just feels like they were in a time travel episode where they are starting back at base.

## Do you consider this suggestion a:

- [] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [] Could (Beneficial to players, there is no important reason to do it

I don't believe the server needs this to operate. But seeing people die and respawn on the SGC where the gate is broken or someone would leave them alone by repeatably dialing their gate, makes me think it will be easier to have people sent straight back where they came from (granted, they have a clone ready) And this mod works over dimensions from the start, which should make coding easier.

**Comment by Tappentine** [comment]
Apologies, its this link https://www.curseforge.com/minecraft/mc-mods/sync for 1.12

**Comment by Joey4213** [comment]
I am extremely sorry to inform you that we have tried adding this mod into the mod pack but it is incompatible with our pack, i will continue to look for a mod that does something similar and is compatible but until then this will not be added. Again, I am sorry and I wish we could have it as well

**Comment by Tappentine** [comment]
Ah damn, thanks for the quick and honest answer Joey. Ill keep an eye out too

**Comment by Joey4213** [comment]
Welcome man, hey if you find anything before I do be sure to contact me so I can test it, I will also see if there is anything I can do to get sync to be compatible

**Comment by Tappentine** [comment]
What's the main issue out of curiosity, is it conflicting mods or something?

**Comment by Joey4213** [comment]
I cant remember 100% but I believe its something to do with constant crashing because of a confliction of mod operations

**Comment by TheRedCreations** [comment]
thats why the core mod is in this modpack

**Comment by Joey4213** [comment]
Coremod for what?!

**Comment by TheRedCreations** [comment]
in the SGMC pack is this mod: 
![grafik](https://user-images.githubusercontent.com/35812887/85019362-fd280a00-b16e-11ea-94eb-003ca16c3259.png)
the core mod for sync

**Comment by Joey4213** [comment]
Dude.. that is a core mod for alot of things, take it out and attempt loading up the pack

**Comment by TheRedCreations** [comment]
![grafik](https://user-images.githubusercontent.com/35812887/85020144-2dbc7380-b170-11ea-8dca-434b172adb6b.png)
not needed core mod

**Comment by Joey4213** [comment]
There is an even better answer for you. :grin:

**Comment by Joey4213** [comment]
Either way its a core mod for more then just sync though...

**Comment by draksterau** [comment]
Reopening this - sorry @Joey4213 I said we'd give it another go :)

**Comment by Joey4213** [comment]
Sounds good to me I'd love to get it to work with us :grinning:

**Comment by Tappentine** [comment]
Hopefully it works out 👍 Looking forward to see how it works with the server if you can tweak it around

**Comment by JayCoolGuy** [comment]
Yeah I think this mod would really fit right in with everything else in this modpack. Also on a side note, taking a look at some of these recipes, they would probably need to be modified to a recipe that is more equal with being able to clone yourself and transfer your consciousness to it. Just mentioning :D.

**Comment by Joey4213** [comment]
yea I would be raise the power required for cloning and also figure out something thats like Asgard level crafting
