### ISSUE TITLE
Bug - ZPM console causes TPS and client lag

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#218]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes
I've added in the schematica mod.

## What would you describe the problem as?
Lag bug? It causes a player near it to lag very much, fps at 0.

## Steps to reproduce the problem
Stand near a zpm console.

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Do not go near a zpm console.  This can be difficult at certain times since they have a chance of spawning next to a stargate.

## What do you expect to happen instead?
The zpm console to not break my game.

**Comment by Joey4213** [comment]
it also occasionally drops the tps to like 0.51 for a minute or so, while loaded that is

**Comment by Joey4213** [comment]
I happen to have an update on this matter, This bug only seems to happen with ZPM consoles that are generated by the stargate structure generation of similar, eg structure generation in general. Otherwise they are fine because I have placed many over the past few days

**Comment by BloodyRussian** [comment]
I have this problem whether it's naturally generated or I place it myself.
