### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#219]
## What is your suggestion?

Stargates with DHDs should have instant (or near instant) chevron locking. Stargates without DHDs, (SGC, all Universe gates, any gate using a computer interface or a PDD) should spin at the various rates designated by their Tier

>Why is this important?
It fits better with the Canon, and MW style stargates dial agonizingly slow, especially with the requirement for 9 chevrons to lock, and the fact that TPS is typically around 15-18, meaning that the default speed is already lowered to 75-90% of normal.

## How will this benefit players?
It would make Milkyway gates more attractive to use, rather than everybody basically having to use a Pegasus gate to not have to wait 90 seconds for a single dial.

It encourages diversity in the use of gates, allowing us to make use of specific gate advantages rather than being limited to Pegasus gates just to do something in a timely manner.

## How will this change for players?
I can't really think of any issues this would present for players, rather than incoming gates dialling faster and having less time to turn on defences, the bigger problem I forsee is backend getting the gate on the incoming side to load quickly enough not to vortex you when you walk in.

## Do you consider this suggestion a:

- [x] Should (Beneficial to players, but can do without)

**Comment by Joey4213** [comment]
check https://github.com/StargateMC/IssueTracker/issues/130

**Comment by BenFRC5147** [comment]
Then add a slight (5-10 second) cooldown to dialling. There are other solutions to something that shouldn't even really be a problem unless a player is specifically trying to be an asshole, and even then, gate locking is canon, it's happened in 2/3 of the source shows, You just have to be able to get your dial out request in before their dial in request happens.

**Comment by Joey4213** [comment]
![image](https://user-images.githubusercontent.com/46541695/85099889-819c7c00-b1b3-11ea-9d10-df4dd1324fc4.png)

**Comment by BenFRC5147** [comment]
Wow thank you for posting a picture of the comment you already linked, I can't read anything except screenshots.

**Comment by BenFRC5147** [comment]
And besides, as my suggestion suggests, you'd only get instant dialling from DHDs, not from any other source, so you cna't write a program that just insta dials some other gate 24/7

**Comment by Joey4213** [comment]
wanna bet? i can make a program to dial a gate 24/7 if i wanted and with these instant dial gates the receiving end will never be able to use their gate because my timing would be so damn precise that they would have to break the gate the moment it shut down because it would instantly re activate

**Comment by Joey4213** [comment]
im just making sure you saw it because that is what bysokar say and as far as im concerned what bysokar says goes above anyone else

so im sorry but unless he has had a change in heart or deems that he will allow instant dialling 100% of the time this matter is essentially closed

**Comment by BenFRC5147** [comment]
![this](https://user-images.githubusercontent.com/13715542/85100188-207da400-b1c5-11ea-8d1d-a9ee7cf17490.png)

**Comment by Joey4213** [comment]
again i say, wanna bet that i cant write a program?

**Comment by BenFRC5147** [comment]
Yes, I want to bet that you cannot in game write a program that will connect to a DHD and dial a stargate, as writing a program that takes control of your player would be an outsie source and therefor the equivalent of a hack, and you would never do that, would you?

**Comment by Joey4213** [comment]
its not considered a hack if i write an outside program as im not breaking any rules of this server for one and two im not doing anything to gain an unfair advantage on players as im just using what was provided to me 😉

**Comment by BenFRC5147** [comment]
You are using something to gain an unfair advantage at that point. You're using an external source to emulate a player so that you can do something faster than should be possible and causing you to lock a player out. 


Using an external program to accomplish something such as this should be against the rules if not already.

**Comment by Joey4213** [comment]
this is an anarchy server essentially for one, and two its not an unfair advantage because if you give me half an hour to retype 9 characters i can do it in a second or less

**Comment by Joey4213** [comment]
and it would take me atleast half an hour to write something to do the same

**Comment by BenFRC5147** [comment]
Oh, so it's anarchy? Let me just grab the latest WURST client then. If you can't see how running an external program to dial stargates in an unintended way is an unfair advantage then just stop replying to this thread.

**Comment by Joey4213** [comment]
i dont know why your fighting this hard for it i already said unless sokar changes his mind this is essentially closed

**Comment by JayCoolGuy** [comment]
Alright lets not change this into an argument between you two.  Sokar says no, so that means, no.  And Ben, stop trying to argue your way through it, it wont change anything and will not benefit anyone.

**Comment by BenFRC5147** [comment]
You could've left it at that too, but you choose to say that you would run scripts on your PC so you could lock somebody's stargate out while you went out for a tea.

I'm 'fighting this hard for it' as its canon, and it makes significantly more sense. I also made a different proposal to the original #130, as that didn't specify only DHDs should get instant locking.

**Comment by Joey4213** [comment]
![image](https://user-images.githubusercontent.com/46541695/85100865-fec8f080-b1b5-11ea-88bc-2a1c5f9a3990.png)

![image](https://user-images.githubusercontent.com/46541695/85100876-05effe80-b1b6-11ea-911c-ac9ed032fb01.png)

**Comment by Joey4213** [comment]
this is closed unless further decided by bysokar

**Comment by BenFRC5147** [comment]
Sokar has not said no to this specific issue, and you closing it because you don't like me is quite unprofessional.

**Comment by Joey4213** [comment]
I'm not closing it because I don't like you, I put all biased feeling aside when handling these thank you very much sir, this is closed unless sokar decides otherwise, thank you for your suggestion

**Comment by BenFRC5147** [comment]
Oh, i'm sure you do

**Comment by Joey4213** [comment]
This is getting very unprofessional Ben I am asking you to stop and be professional about this or just stop entirely.
Thank you.

**Comment by JayCoolGuy** [comment]
Tbh Ben, Joey stayed professional in this issue, he didn't display any unfair treatment towards you.  So please at this point give up until Bysokar changes his mind.

**Comment by BenFRC5147** [comment]
I was ready to stop at just my original issue, you then brought up a marginally related issue, saying that it was exactly the same and was open and shut denied. Then you said you'd use a script to enable you to lock out a stargate using my suggestion with an unfair advantage. You could've just left it at good enough, but you just had to attack every angle rather than just leaving it for sokar or closing it instantly.

**Comment by Joey4213** [comment]
If he changes his mind, I'm not sure he will.

**Comment by draksterau** [comment]
I rejected  this for two reasons:

- A good chunk of the time it takes to spin is time currently used to load worlds that are dormant. There will be a delay once all the chevrons lock anyway if we allow 'instant locking'... because the world has to load before the wormhole can open.

- The dial out time reduces lag on the server because it means you cant keep a world loaded by constantly dialling them - there will be points where the world is unloaded in between dials.

I agree a good workaround would be to only allow this on DHDs that require manual user intervention.... so we cant script it.

Question though - Dont universe gates still spin once you enter an address and lock each chevron individually?

**Comment by JayCoolGuy** [comment]
they do

**Comment by BenFRC5147** [comment]
They do, which is why I listed them in the exclusions. There was never a DHD for them and Kinos didn't autolock chevrons which implies portable diallers wouldn't autolock either.

**Comment by draksterau** [comment]
> They do, which is why I listed them in the exclusions. There was never a DHD for them and Kinos didn't autolock chevrons which implies portable diallers wouldn't autolock either.

Right, so you're mainly thinking Pegasus and MilkyWay variants....

Question how do we explain the slow spin/lock of MilkyWay receiving gates when the source dialling in used a DHD?

**Comment by BenFRC5147** [comment]
It didn't, when it got dialled into the locked the 7 chevrons in quick succession and then the vortex appeared

**Comment by BenFRC5147** [comment]
Well it appears to do both, but it _should_ just lock all 7 in quick succession and lock. It was either do to goofs or for drama that it did the opposite I imagine

**Comment by Joey4213** [comment]
@BenFRC5147 https://www.youtube.com/watch?v=gu9xm-SMEWk

**Comment by BenFRC5147** [comment]
https://stargate.fandom.com/wiki/Incoming_Wormhole

**Comment by Joey4213** [comment]
![image](https://user-images.githubusercontent.com/46541695/85104401-620a5100-b1bd-11ea-8676-e0d96bcdbc07.png)

**Comment by BenFRC5147** [comment]
Yes, you've indicated the line before the important information, now please continue to read now that you think you've made a point.

**Comment by Joey4213** [comment]
![image](https://user-images.githubusercontent.com/46541695/85104565-aeee2780-b1bd-11ea-8bb6-323110d49fce.png)

**Comment by BenFRC5147** [comment]
I misread the line. My bad. But the incoming gate would have to 'spin' at a speed equivelant to the instant locking or else a traveller would get to the recieving gate where there was no event horizon. But if you look at the anubis dialling in episode the chevrons all insta locked no spinning.

**Comment by Joey4213** [comment]
anubis was partly ascended so he had all that knowledge so ofc he can do smth like that

**Comment by BenFRC5147** [comment]
There are also instances of dialling FROM the SGC to planets where the ring doesn't spin but the chevrons come on one at a time slowly, indicating it's linked to the speed that the dialling gate can lock chevrons

**Comment by Joey4213** [comment]
can we be fair and say the way that they showed gate dial in and out was really shotty so we are going to keep contradicting each other

**Comment by SunnyM00n** [comment]
What if the DHDs would cause the gate to dial when a glyph is entered? (The Gate begins spinning and locks until the last inputted glyph is dialed) This would speed things up. And with a slightly increased dialing speed for all gates, all gates would be canon. The SGC gate is so slow because it is simply manually dialed each time they use it. (Ring moved by an external motor)

**Comment by Joey4213** [comment]
no it didnt, the rings movement was part of the gate itself wasnt it?

**Comment by BenFRC5147** [comment]
I think eventually they were able to communicate with the control crystals to tell it to spin one way or another, but I don't know why at that point they wouldn't tell it to instalock. But I imaigne initally they just spun it with a motor (Ernest's dial, probably early Pre-Abydos) We dont see any motor but it could be under the embarkation ramp

**Comment by Joey4213** [comment]
pre-abydos they spun the gate manually i cant remember what episode but its shown
and its unlikely that the motor is below the ramp because you need it to touch the inner ring

**Comment by BenFRC5147** [comment]
The ring did extend slightly below the ramp tho

**Comment by Joey4213** [comment]
oh, yea thats right i forgot about that xD

**Comment by SunnyM00n** [comment]
Ehem: “Soon, Carter sped up the dialing to secure the Stargate from an off-world activation by Sokar. However, as the dialing computer continued to rely on manually rotating the ring and locking the chevrons, the system by design never approached the speed that could be achieved by dialing with a DHD, taking about a minute to dial an address when not accelerated.”
