### ISSUE TITLE
Suggestion - Adding ZPM Crafting

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#222]
I want implement some crystals from Tier 1 up to Tier 10 into my Asgard Beam Mod. only with T10 items you can craft a ZPM. I planned with T1-T10 to make it very expensive. I make it only if you allow it.

**Comment by Joey4213** [comment]
Bysokar doesnt particularly want a zpm crafting recipe but if you get enough people to upvote this then I will add it 😉

**Comment by TheRedCreations** [comment]
I think that's possible. But don't forget the idea with crystals from tier 1 up to tier 10

**Comment by Joey4213** [comment]
If you want to design crystal textures you can, or we could use the ones from 1.7, and what type of crystal are you thinking... energy? Or smth else

**Comment by TheRedCreations** [comment]
mainly energy

**Comment by Joey4213** [comment]
Coolio so that won't be super difficult and can be done, if you can pm me a list of crystals types and with information about each and i start work on then soonish

**Comment by Joey4213** [comment]
I would like 4 more votes to make this official though, if we can get 4 more votes I would be in for it

**Comment by Joey4213** [comment]
ok so byso yelled at me last night to add a crafting recipe so i will start on this project :D

**Comment by draksterau** [comment]
@Joey4213 Need to have all items craftable. ZPMs will compete with induction matrices but have the benefit of being much smaller, to give you an idea of how difficult they need to be.

**Comment by Joey4213** [comment]
gottcha

**Comment by TheRedCreations** [comment]
I guess this can be closed now. Update is already online.

**Comment by Joey4213** [comment]
yea sorry XD
