### ISSUE TITLE
Bug - Tick Dynamics and AE2

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#224]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>0.0.319

## Did you receive an error message? If so, copy it here.
>N/A

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>Added Mods:
More Overlays
JEIIntergration
Simple-Ignore
Ingame Account Switcher
HWYLA

## What would you describe the problem as?
>Occasionally, something will cause ME systems to 'Reset' meaning that it'll reinitialize all channels. Typically this isn't a huge problem, but if you have stuff on P2P channels (as I, and most complex systems do) this causes quite a problem, as they take significantly longer to reboot, meaning all of my Storage drives stay offline for a good 20 seconds each time this happens.

This has only been occurring the past few days, apparently since 'Tick Dynamics' was installed

## Steps to reproduce the problem
>Use an ME system with several P2P channels, and wait. No real trigger, just occurs seemingly randomly

## How often can you reproduce the issue?
None of the above, it's intermittent 

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>You can elect to just ignore it and it'll be mostly fine, I typically get around 6-10 minutes of uptime between strange ticks where it resets.

## What do you expect to happen instead?
>The ME system does not periodically reset causing P2Ps to temporarily go offline disabling larger systems

**Comment by draksterau** [comment]
Tick Dynamic was removed... so this no longer applies.
