### ISSUE TITLE
Suggestion - Integrate Mekanism Induction Matrices with Stargates

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#226]
## What is your suggestion?
>Mekanism's Induction Matrices are multiblocks configurable power banks, they consist of Providers and Cells, providers dictating how much PowerUnit/t can go out, and Cells dictating overall power storage, I'm proposing that these be given a direct intergration with stargates, where with enough providers and cells, it can be used to power massive distance dials. Think of it like the destiny power banks but not destroyed. These also charge at normal rates, so it's not like free energy, just  a large capacitor that can provide power at an extreme rate.

## How will this benefit players?
>Give players an expensive yet achievable way to dial destiny and other faraway locations

## How will this change for players?
>Allow them to trickle charge a capacitor and then be able to dial a faraway planet when they've got the juice. This would be one way unless they set up infrastructure on the other end.

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [ ] Could (Beneficial to players, there is no important reason to do it

**Comment by draksterau** [comment]
I don't mind this idea of this actually - will see if Mek will allow me to use it as an SG Energy source.
