### ISSUE TITLE
Suggestion - A way to dial any Gate from protected Planet in the same galaxy

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#227]
Sunny and I want a way, to dial any Planet in the same Galaxy from a protected Planet or Station. We want for the NPC an input field to enter the Address we want to dial, cause PDD's are Disabled on protected Planets/Stations

- [ ] Add an address field to the dial NPC

**Comment by Joey4213** [comment]
@TheRedCreations the reason we removed the ability to dial out from protected area freely is because they use no power so you can dial anywhere in the universe and we want to prevent that so this will sadly not be fixed.
Sorry bud. 
Best regards Joey.

**Comment by TheRedCreations** [comment]
i said in the same Galaxy... not universe

**Comment by Joey4213** [comment]
Oh crap... lol I'm so sorry lol I read that wrong I my mind just kinda blanked out the anywhere in galaxy part.

**Comment by Joey4213** [comment]
But yea I do agree with you on that its a good idea. :grin:

**Comment by TheRedCreations** [comment]
thanks

**Comment by draksterau** [comment]
The only way to do this is through the redial mechanic, which is ingame. 
I cant modify CustomNPCs to support this and don't plan on allowing players to manually dial out from protected areas - it makes it so players could then conflict with eachother too much.
