### ISSUE TITLE
Bug - Players and rockets get stuck at Y998 when transferring between dimensions

### ISSUE THREAD

**Issue by Lonestargazer** [StargateMC/IssueTracker#228]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>0.0.322
.

## Did you receive an error message? If so, copy it here.
>No

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

.

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>Nothing

## What would you describe the problem as?
>[Im trying to land on some planet but my rocket will stuck on 998  height and when the fuel is depleted the rocket will fall back on launchpad.

.

## Steps to reproduce the problem
>[Build rocket, build a station then warp to some planet and try to land there.

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>[Idk maybe its a bug in my client but maybe you can try to fix it in next update

## What do you expect to happen instead?
>[I would like to land on planet which im orbitting with my ship/station

**Comment by Joey4213** [comment]
I will look into it later today thanks for the report

**Comment by Joey4213** [comment]
I have not had the same issue, and I have repeatedly attempted to recreate so it seems that you are the soul bugged person with this, I will close it for now but if you continue to have this happen please contact me
