### ISSUE TITLE
Bug -  Stargates don't drop upgrades when broken

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#229]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>1.0.0.0

## Did you receive an error message? If so, copy it here.
>No

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>Simple Ignore
HWYLA
MoreOverlays
JEIIntergrations
Ingameaccountswitcher

## What would you describe the problem as?
>Stargates when broken do not drop gate upgrades

## Steps to reproduce the problem
>Break a stargate base block that has been upgraded to either a milky or Pegasus variant

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Don't break gates

## What do you expect to happen instead?
>The stargate drops all applied upgrades when broken

**Comment by draksterau** [comment]
Fixed in v1.0.1.0
