### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Joey4213** [StargateMC/IssueTracker#232]
[SGcraft.zip](https://github.com/StargateMC/IssueTracker/files/4811563/SGcraft.zip)
I already forked it into the server, you just need to review and approve it

Adds ZPM crafting
Modifies Stargates To be slightly more fair in crafting

**Comment by TheRedCreations** [comment]
i think the gate is now better. thanks

**Comment by draksterau** [comment]
Thanks! For future reference, you should offer a pull request or comment on the original issue.

**Comment by Joey4213** [comment]
ah right, kk will do and @TheRedCreations yea I looked at them and thought "yea this is kinda unfair"
