### ISSUE TITLE
Bug - Stargates in Live draw significantly large amounts of power

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#234]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>1.0,1.0

## Did you receive an error message? If so, copy it here.
> Only 0.005% of required ZPM or Induction Matrix provided energy is available 

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>Simple-Ignore
HWYLA
MoreOverlays
InGameAccountSwitcher
JEIIntergrations

## What would you describe the problem as?
>Attempting to dial destiny yields the above error message with 16 Ultimate providers
## Steps to reproduce the problem
>Create an induction matrix, use any number of providers less than 325,000, and attempt to dial destiny. It will not work and will produce a low energy error

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] No

## How to work around the issue
>You cannot dial destiny, no workaround

## What do you expect to happen instead?
>Destiny should be reachable with around 500ish Ultimate Providers as was in test, or maybe more if needed for balance, but should not be requiring 320K ultimate providers to initiate a connection (Trust me, I did the math. 16 is 0.005% of roughly 320,000)
This is not only larger than the volume of the destiny itself, an absolutely insanely large amount of materials to craft, it is also impossible. Max size for a mekanism induction casing is too small to fit even a sizeable portion of this number in there. Even if you got 12 full size induction casings this would not come close. (12 is the max number of full size you can fit within the range)

**Comment by BenFRC5147** [comment]
This also makes 'small' intergalactic wormholes super expensive too, To Atlantis from earth is 12.1GRF/t Estabilishing

**Comment by draksterau** [comment]
Fixed in 1.0.2.0 - Reduced all power use by a factor of 100.
