### ISSUE TITLE
Bug - Long Distance Dials

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#237]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>1.0.1.0

## Did you receive an error message? If so, copy it here.
>No

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>Simple-Ignore
Hywla
JEIIntergrations
Ingame account switcher
moreoverlays

## What would you describe the problem as?
>Attempting to dial destiny with enough providers in a Mekanism induction matrix will dial, but then upon locking the 7th(? probably unrelated issue, but strange nonetheless) chevron, will immidiently disconnect. No power draw is reported in induction matrix as far as I can tell.

## Steps to reproduce the problem
>Fill an induction matrixx with enough providers to dial destiny from Milky, and attempt to dial

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Dialling destiny isn't required to play the game, so no real workaround is needed to continue playing

## What do you expect to happen instead?
>When you have enough providers to open the gate to destiny, it should open.

**Comment by draksterau** [comment]
This should now be resolved. Please let me know if you have any further issues @BenFRC5147
