### ISSUE TITLE
Bug - ETA on Holo projector

### ISSUE THREAD

**Issue by DEVensiv** [StargateMC/IssueTracker#238]
## Version of the StargateMC Client
>1.0.3.0

## Did you receive an error message? If so, copy it here.
>hehe no

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] No

## What would you describe the problem as?
>The Holo planet selector (Advanced Rocketry) shows wrong (old) ETA for travel time.

## Steps to reproduce the problem
>Place a Holo Planet Selector and look at the ETA

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Just /5 the time seen

## What do you expect to happen instead?
>show the correct time (since contributors should have a benefit in time to i guess)

**Comment by draksterau** [comment]
Fixed ahead of next release
