### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Tianbether** [StargateMC/IssueTracker#244]
## What is your suggestion?
> Add inventory tweaks to the server.

>Why is this important?
> It allows for fast inventory and chest sorting.

## How will this benefit players?
> It is a good quality of life mod making it easier for players to see how much they have of a resource and easier to find it.

>Why is this important?
> It makes sorting and using resources a lot easier for players.

## How will this change for players?
> They can easily find and sort resources.

>Why is this important?
>Knowing potential impacts or changes to the way players have to do things is important]

## Do you consider this suggestion a:

- [x] Should (Beneficial to players, but can do without)

>Why is this important?
> It really just eases sorting and makes it easier to organizing resources.

**Comment by mainesi** [comment]
Hi Tian,

While I agree this is a better mod to have. It is a client side mod and can be added without being server side.
Also for better sorting you can get yourself an ME system which will group all your items together
