### ISSUE TITLE
Suggestion - Enable normal mobs.

### ISSUE THREAD

**Issue by Tianbether** [StargateMC/IssueTracker#248]
## What is your suggestion?
> Enable normal minecraft mobs to spawn since the server is now a lot better it should not affect performance unless people make giant mob farms.

>Why is this important?
> A lot of recipes and machines need minecraft mob drops.

## How will this benefit players?
> Since a lot of recipes need mob drops it would allow people to easier make machines and items.

>Why is this important?
> It allows us to make machines and items that are otherwise almost impossible to make.

## How will this change for players?
> It will make the game slightly easier for people.

>Why is this important?
> It just makes it easier for people.

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [ ] Could (Beneficial to players, there is no important reason to do it

>[Why is this important?
> Some items are nearly impossible to make until you get extremely far into the game and even then they are a pain to get.

**Comment by kieranmogs** [comment]
+1
