### ISSUE TITLE
Client Crash - 

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#254]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>1.0.8.2

## Can you find your crash on OpenEye (https://openeye.openmods.info/crashes)?
- [x] Yes

## Link to Crash Report (OpenEye or Pastebin)
https://openeye.openmods.info/crashes/d1f427cfdad2177afc8d01ccf44c65cf
https://openeye.openmods.info/crashes/5c9462452888ab4be9f4331a8fa9f405

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
-Bookshelf
-Gamestages
-Hwyla
-journeymap
-wailaHarvestability
-wailaStages

## Steps to reproduce the crash
>Using AE Crafting Terminal and try to craft

## How often can you reproduce the crash?
- [x] Always

## Can you continue playing after the crash occurs and you re-load the client?
- [x] Yes

## What do you expect to happen instead?
>No crash

**Comment by SunnyM00n** [comment]
Same issue on my side

[latest.log](https://github.com/StargateMC/IssueTracker/files/4841279/latest.log)

**Comment by draksterau** [comment]
Resolved as of 2 hours ago @SunnyM00n @TheRedCreations
