### ISSUE TITLE
Bug - Not enough memory

### ISSUE THREAD

**Issue by Lonestargazer** [StargateMC/IssueTracker#255]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
1.0.8.2

## Did you receive an error message? If so, copy it here.
No

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
Nothing

## What would you describe the problém.
When the game is started i have 5 gb of space andwhen the game is loaded i have only 200mb of it.

## Steps to reproduce the problem
Download game. Start game. Game crashed.

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?

- [x] No

## How to work around the issue
I don't know

## What do you expect to happen instead?
Normal game

**Comment by Joey4213** [comment]
raise allocated memory?

**Comment by draksterau** [comment]
@Lonestargazer StargateMC requires 6GB of memory allocated, not 5.
