### ISSUE TITLE
Client Crash - Applied Energistics

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#256]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>Latest as of post time

## Can you find your crash on OpenEye (https://openeye.openmods.info/crashes)?
- [x] Yes

## Link to Crash Report (OpenEye or Pastebin)
>https://openeye.openmods.info/crashes/d1f427cfdad2177afc8d01ccf44c65cf

## Did you receive an error message other than the crash report? If so, copy it here.
>No

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] No

## Steps to reproduce the crash
>I was trying to craft in AE and I had the three Iron ingots on the top row and it said it was making a iron pressureplate rather than the recipe I wanted. I then attempted to autocraft some water buckets but this did not work, my ae system crashed, then when I tried manually inputting the three iron it crashed me.

## How often can you reproduce the crash?
- [x] Always

## Can you continue playing after the crash occurs and you re-load the client?
-[x] yes

## How to work around the issue
>Don't make anything with three iron in top row it seems.

## What do you expect to happen instead?
>it doesn't crash? idk man

**Comment by draksterau** [comment]
This is resolved as of 2 hours ago.
