### ISSUE TITLE
Mod Addition - Carpenter’s Blocks

### ISSUE THREAD

**Issue by kieranmogs** [StargateMC/IssueTracker#258]
## What is your suggestion?
>Carpenters Block mod adds the ability for ramps, slopes, stairs block with the ability to have any material as long as you have the block to put on it

>Why is this important?
>It significantly makes building more interesting/look better for instance ha'taks and the like can actually be smooth ramps instead of having a bumpy block look

## How will this benefit players?
>The ability to make better looking buildings and uses different materials as stair/fence/ramp blocks that normally only have the default solid block option

## How will this change for players?
>a few of us will have to go back through our builds to pretty them up which will defiantly take time, but apart from that nothing much would change 

## Do you consider this suggestion a:

- [x] Could (Beneficial to players, there is no important reason to do it

**Comment by mainesi** [comment]
Hi,
thanks for the suggestion

However, we have two mods that do the same or similar.

- Blockcraftery: https://www.curseforge.com/minecraft/mc-mods/blockcraftery

and 

- ArchitectureCraft: https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev

**Comment by Joey4213** [comment]
Tech seems to have taken care of this, and I could not have said better, I will be closing this now.
