### ISSUE TITLE
Suggestion - Alter the recipe for Skeleton Skull Head

### ISSUE THREAD

**Issue by BenFRC5147** [StargateMC/IssueTracker#283]
[Please fill out the form below and delete the sections in square brackets after reading them]

## What is your suggestion?
>Alter the recipe for Skeleton Heads (The base item required to make carbon stars) To not require bones.

## How will this benefit players?
>Requiring bones for a skeleton head means that getting any significant number of Activated Carbon Stars is tedious at best, downright impossible at worst. Changing this requirement to something more suiting of the name "Carbon Star" such as coal would be ideal, allowing creating Activated carbon stars without killing hordes and hordes of mobs.

## How will this change for players?
>It will create more accesibility to Activated Carbon Stars, which are useful for creating some mid to high tier tech,

## Do you consider this suggestion a:

- [x] Should (Beneficial to players, but can do without)

**Comment by Joey4213** [comment]
no longer has a point as the molecular assembler no longer exists
