### ISSUE TITLE
Suggestion - Disallow NPCs spawning inside lit up areas like vanilla mobs.

### ISSUE THREAD

**Issue by Tianbether** [StargateMC/IssueTracker#285]
## What is your suggestion?
> Disallow Tauri and Goa'uld from spawning inside people's bases when they are lit up by torches.

## How will this benefit players?
> It will allow players with big bases with walls from having to worry about NPCs spawning inside the walls and shooting them or their tamed animals. As of right now I have had to find new animals 3 times due to NPCs spawning inside my lit up barn and killing the animals in the pens.

## How will this change for players?
> It will allow players to build safe areas for them and their animals.

## Do you consider this suggestion a:
- [x] Should (Beneficial to players, but can do without)

**Comment by Joey4213** [comment]
#114

**Comment by Joey4213** [comment]
#164

**Comment by Joey4213** [comment]
similar to 164
closing...

**Comment by Tianbether** [comment]
I am neither underground or on top of a mountain, my base is a walled in compound with a few buildings so #114 and #164 do not really fix my problem since they will still spawn outside my buildings and walk in. That is already happening since my doors and animals keep getting destroyed/killed by the NPCs when they walk in when I am offline and other people are rendering my base.

**Comment by Joey4213** [comment]
Tian, the npc's will not spawn under a roof and if you put the gate near your house then they wont spawn near your house, bam problem solved, or get a turret to kill the npc's, we have also stopped the npc's from killing animals you should see it by them not killing either now, or in the next update I'm not sure if npc logic was updated on live yet
