### ISSUE TITLE
Bug - Space Dimension duplicated !IMPORTANT!

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#286]
We have currently 2 Space dims. Dim-2 and Dim-2147473648. The last one is a duplication from the first. Remove Dim-2147473648

**Comment by Joey4213** [comment]
ok how do I recreate it, I cant fix it if I cant re-create it

**Comment by mainesi** [comment]
Ok guys i have been to this duplicate dimension. I am not sure how this was created
I will try get Bysokar to look at it

**Comment by Joey4213** [comment]
ok but im trying to help with bysokars efforts by doing things while he is at work/sleep essentially im trying to be the day dev.. so information would be nice

**Comment by mainesi** [comment]
yes but u cant delete an entire dimension from the server

**Comment by Joey4213** [comment]
well yes but I would like to stop it from being regenerated..

**Comment by draksterau** [comment]
@Joey4213 Great attitude, but you're about 2 years of learning away from that man :)

Ill take a look now. Thanks @mainesi @Joey4213

**Comment by Joey4213** [comment]
Me an dev talked about something, we might not be able to delete it...

**Comment by Joey4213** [comment]
Bysokar says there is nothing wrong so I will be closing this now.

**Comment by draksterau** [comment]
Hi Guys,
The server has no evidence of second space dimension existing.

I've checked the logs and there is evidence that somones station ID got changed to that ID number then moved to orbit the overworld.

Let me know your station ids and Ill check they are ok.

Byso

**Comment by draksterau** [comment]
Ive reviewed ARs code and stations in warp get given a virtual dimension id. Guess what it is...
This is simply a station being corrupted, theres no extra dimension.

Again, need station ids or I cant troubleshoot further.

**Comment by draksterau** [comment]
I cant find any evidence
