### ISSUE TITLE
Bug - Broken Molecular Transformer after unboxing

### ISSUE THREAD

**Issue by RicoPeav** [StargateMC/IssueTracker#291]
## What would you describe the problem as?
> I put my molecular transformer within a cardboard box while it was transforming an item, but when I placed the box down and unboxed the transformer, it was just a black and purple error block thing so I tried to break it to get the transformer back, but nothing dropped.

## Can you work around the issue and continue playing?
- [x] Yes
- [  ] No

## What do you expect to happen instead?
> For the molecular transformer to show and be functional after unboxing it.

**Comment by Joey4213** [comment]
This is because of the way Mekanism handles boxing ic2 machines, I will exclude all ic2 machines from the list to make sure this doesn't happen.

**Comment by RicoPeav** [comment]
Alright

**Comment by Joey4213** [comment]
Molecular transformers no longer exist, so this is kinda fixed i guess
