### ISSUE TITLE
Bug - Cannot interact with some npcs  which are needed to get quests or operate gate at SGC on Live server.

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#299]
## Version of the StargateMC Client
>v2.5.9

## Did you receive an error message? If so, copy it here.
[14:41:55][SEVERE/CustomNPCs][noppes.npcs.client.PacketHandlerClient:68] Error with EnumPacketClient.DIALOG
[14:41:55][SEVERE/CustomNPCs][noppes.npcs.client.PacketHandlerClient:68] java.lang.NullPointerException
	at noppes.npcs.client.gui.player.GuiDialogInteract.appendDialog(GuiDialogInteract.java:279)
	at noppes.npcs.client.gui.player.GuiDialogInteract.<init>(GuiDialogInteract.java:50)
	at noppes.npcs.client.NoppesUtil.openDialog(NoppesUtil.java:198)
	at noppes.npcs.client.PacketHandlerClient.client(PacketHandlerClient.java:169)
	at noppes.npcs.client.PacketHandlerClient.lambda$onPacketData$0(PacketHandlerClient.java:66)

## Where are you playing?
- [. ] Single Player
- [x] MultiPlayer (StargateMC.com)
- [. ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes
- [. ] No

## Detail what you have modified in the client here, if applicable
Classic Bars (HUD Visual)
AppleSkin (HUD Visual)

## What would you describe the problem as?
Interface issue where in some cases the NPC does not respond at all and no visual errors are thrown.
(This seems to only affect NPCs with dialog wheels or conversations)

## Steps to reproduce the problem
Try to interact with some of the NPCs at SGC and see if any of them respond.

## How often can you reproduce the issue?
- [x] Always
- [. ] Most of the time
- [. ] Some of the time
- [. ] Rarely

## Can you work around the issue and continue playing?
- [. ] Yes
- [x] No

## How to work around the issue
Not sure what could be causing it so unable to find work around.

## What do you expect to happen instead?
Should be able to open conversation interface to access some menus, start quests or begin dialing out. 
For example, Walter handles gate control at the SGC so cannot dial out otherwise meaning any players, mostly new players, would be stuck at spawn with no alternate means to leave the starting area.

**Comment by draksterau** [comment]
Thanks @NovaLynxie … for now the only workaround is to relog.
This is actually a bug in CustomNPCs, but @Noppes refuses to acknowledge or fix it.
I can reproduce with just forge and CustomNPCs installed :(

**Comment by CaptainNikolaus** [comment]
@draksterau says issue is fixed
