### ISSUE TITLE
Bug - NPC Quest

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#300]
Unable to complete Quest cause NPC
![grafik](https://user-images.githubusercontent.com/35812887/87250178-7f040e00-c463-11ea-8f86-85d4fb60978a.png)
![grafik](https://user-images.githubusercontent.com/35812887/87250184-83302b80-c463-11ea-98a3-bf3d67627ab6.png)

**Comment by draksterau** [comment]
Will fix ASAP
