### ISSUE TITLE
Suggestion - Add Different Stargate Blocks for each tier instead of upgrade

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#303]
## What is your suggestion?
>[Describe what you're suggesting in as much detail as you can] 
Tier 1 and 2 of stargates requires an upgrade crystal to upgrade to the next tier.  I think that each tier should have their own blocks, chevron blocks, ring blocks, sg bases.

## How will this benefit players?
It doesn’t benefit the player and really but makes the game more realistic and interesting. 

## How will this change for players?
Players will have to work more I think to upgrade the gate tiers.

## Do you consider this suggestion a:

- [x] Could (Beneficial to players, there is no important reason to do it

**Comment by Joey4213** [comment]
moved to correct space 👍
