### ISSUE TITLE
Task - Standard options.txt and optionsof.txt with keybinds that don't conflict

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#304]

**Comment by draksterau** [comment]
@Nerion1 how you doing with this bud?

**Comment by Nerion1** [comment]
Options are all configured, just need to do controls now!

**Comment by Nerion1** [comment]
Okay so settings are set to run as fast/smooth as possible and have been tweaked so as to not ruin the visuals too much for people. If there is still some lag you can set the following:

Quality > Better Grass: Fast
Quality > Clear Water: Off
Quality > Connected Textures: Fast
Details > Trees: Fast

Controls have been tweaked to remove as many conflicts as possible. If you come across any, please let me know!
Voxel map is now controlled by using "Shift + <key>" i.e Shift+X to see full screen map.

[options.txt](https://github.com/StargateMC/IssueTracker/files/4991772/options.txt)
[optionsof.txt](https://github.com/StargateMC/IssueTracker/files/4991773/optionsof.txt)

**Comment by draksterau** [comment]
Added in v3.8.0
