### ISSUE TITLE
Dis-allow IRIS on universe gate

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#305]
- [x] Players should be informed that the iris upgrade is only applicable to MilkyWay and Pegasus gate types
- [ ] Attempting to install the iris should fail and inform the player why
- [x] The upgrade item should state Iris support as a perk of T2 gates

**Comment by draksterau** [comment]
@Joey4213 you nearly done with this bud?

**Comment by Joey4213** [comment]
yea i just need to push it after double checking, will do tonight :)

**Comment by draksterau** [comment]
@Joey4213 If you dont want to do anything for server anymore thats fine bud...

**Comment by Joey4213** [comment]
no, i want to do stuff with the server, i have just been passing out lately in the middle of working and then i get up and forgot to push this until midday, and i was going to push it yesterday but github desktop client was being mean, so im redoing all of it right now and making sure it works correctly and not all fucky

**Comment by Joey4213** [comment]
pull req open
