### ISSUE TITLE
Add a Stargate Hypervisor

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#328]
I suggest to add the Ability to have multiple Gates on the same Planet and to choose from which gate you want to dial. The gates would have to be in a certain range to each other to ensure that it can't be misused. This would allow player made "Gate Hubs". For example: I do want to use the Universe gate Style, but I also want to dial to other galaxies. This would allow the usage of both without breaking one of the Gates. (This is canon: Midway operates like this and the official Comics introduce an Ancient made Gate Hub)

**Comment by Luckyradkid1** [comment]
i think this would be nice as well

**Comment by JayCoolGuy** [comment]
Midways gates only worked because they were tweaked and altered to. Perhaps this could be an option in the sg configurator to be able to do this or as an upgrade item.

**Comment by SunnyM00n** [comment]
This is the structure I have in mind: [Gate Hub](https://stargate.fandom.com/wiki/Stargate_hub)

**Comment by draksterau** [comment]
I might allow this when orbiting a star when I have it working. Or I might create some 'pockets' of stars/void zones you can travel to and only allow this outside a galaxy.

**Comment by draksterau** [comment]
This is going to only be possible in a protected area scenario sorry. Midway, and another hub area if we decided to make one, for example.

**Comment by luckyrada** [comment]
sad
