### ISSUE TITLE
Bug - Orbital mining laser won't turn on.

### ISSUE THREAD

**Issue by Tianbether** [StargateMC/IssueTracker#329]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
> latest version.

## Did you receive an error message? If so, copy it here.
> No.

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [x] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes
- [ ] No

## Detail what you have modified in the client here, if applicable
> Applehud

## What would you describe the problem as?
> I make a mining laser, give it a lens and power and it wont mine when given a redstone signal.

## Steps to reproduce the problem
> Make a orbital mining laser and turn it on.

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
> You can not.
## What do you expect to happen instead?
> The laser mining the planet.

**Comment by Joey4213** [comment]
The Miner works just fine, I just used it yesterday, it just takes some learning to use. Once we get our wiki going I will explain it there, but for now just look at the official AR wiki.

**Comment by kieranmogs** [comment]
@Joey4213 Is does not work right now, as ive replaced all my ones, and none of them fire and i know full well how to set them up as sokar can attest to.

**Comment by Joey4213** [comment]
I confirmed it worked on the day that this post was created you guys must be doing something wrong, so unless you wanna test with me since you guys can recreate it.

**Comment by Joey4213** [comment]
My orbital Laser is still operational...

**Comment by Joey4213** [comment]
i was right..... they work fine confirmed by everyone that said they had issues...
