### ISSUE TITLE
Suggestion - add diseases

### ISSUE THREAD

**Issue by luckyrada** [StargateMC/IssueTracker#330]
## What is your suggestion?
add diseases
>Why is this important?
it would make survival more hard and fun.

## How will this benefit players?
well, dosnt really benifit them xD 

## How will this change for players?
would make survival harder, and they would have to get cures to the diseases

>Why is this important?
becuase surviving is pretty easy right now, and i think it needs more to make it harder.
## Do you consider this suggestion a:

- [] Must (Important to keep players happy)
- [x] Should (makes survival harderl to players, but can do without)
- [] Could (Beneficial to players, there is no important reason to do it

>other?
think like you could research cures? and like the more dangerous the disease the rarer it is? and like it only happens on planets unless infected person goes onto ship?

**Comment by Joey4213** [comment]
ah yes i will be making covid-20 in game
it is the next gen of covid

**Comment by luckyrada** [comment]
mhm

**Comment by draksterau** [comment]
https://www.curseforge.com/minecraft/mc-mods/tough-as-nails?

**Comment by luckyrada** [comment]
Ooo yeah on your planets u get hyperthermia instead of getting set in ducking fire xD

**Comment by Nerion1** [comment]
Tough as Nails is end of life. No need for this mod currently. Would be nice.
Closed.
