### ISSUE TITLE
Suggestion - Holomap Change

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#335]
## What is your suggestion?
>Change the holomap so you’re able to select a few planets from each other galaxy. This keeps the lag still lowered from what it was when all parts of each galaxy were displayed.

## How will this benefit players?
>Players who prefer to use the holo map when warping rather than the warp controller can do so.

>Why is this important?
>Personally I find the holo map a lot easier to use than the warp controller.

## How will this change for players?
>Players can continue to use the holo map to warp while keeping lag reduced.

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [ ]Could (Beneficial to players, there is no important reason to do it

**Comment by Joey4213** [comment]
I don't think this should be added because it would be a waste of bysokar's coding time, and isn't needed, just select a planet from another galaxy, warp there and then use the holo from that point.

**Comment by draksterau** [comment]
Yeah not expanding it - Im even tempted to only show a portion of a galaxy to players using a holo.

**Comment by draksterau** [comment]
@JayCoolGuy FYI the reason is to keep the entity count down. The holo is a lag machine.
