### ISSUE TITLE
Suggestion - AUNIS Naquadah Shard Crafting Recipe Change

### ISSUE THREAD

**Issue by CaptainNikolaus** [StargateMC/IssueTracker#336]
[Please fill out the form below and delete the sections in square brackets after reading them]

## What is your suggestion?
Change the current recipe for the AUNIS Naquadah shards from SGCraft Naquadah surrounded by 4 lava buckets to just putting it into the enrichment chamber. Would make crafting it less cumbersome for those wishing to obtain it. Even if it took 2 SGCraft naquadah in the enrichment chamber to make it, so you can't convert it 1:1

## How will this benefit players?
Can allow slightly easier access to making ring platforms and such

## How will this change for players?
Look at above?
## Do you consider this suggestion a:
- [x] Should (Beneficial to players, but can do without)
- [x] Could (Beneficial to players, there is no important reason to do it

**Comment by Joey4213** [comment]
what do you need the shard for? it doesnt currently have any crafting usage to my knowledge @CaptainNikolaus

**Comment by CaptainNikolaus** [comment]
yeah it does, transport rings buddy

**Comment by draksterau** [comment]
@Joey4213 You have closed this without posting a new recipe?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: CaptainNikolaus <notifications@github.com> Date: 31/7/20  6:11 pm  (GMT+10:00) To: StargateMC/IssueTracker <IssueTracker@noreply.github.com> Cc: Bysokar <draksterau@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [StargateMC/IssueTracker] Suggestion - AUNIS Naquadah Shard Crafting Recipe Change (#336) 
yeah it does, transport rings buddy

**Comment by Joey4213** [comment]
whoops, i pushed the wrong button when i commented...

**Comment by Joey4213** [comment]
@CaptainNikolaus will add new recipe for the shards 👍

**Comment by CaptainNikolaus** [comment]
Done by myself
