### ISSUE TITLE
Bug - Transport Rings can still be used even they're removed

### ISSUE THREAD

**Issue by CaptainNikolaus** [StargateMC/IssueTracker#338]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v3.1.5

## Did you receive an error message? If so, copy it here.
No error message

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [x] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## What would you describe the problem as?
Breaking the Transport Ring block and leaving the Controller still allows you to ring to other Transport Rings
## Steps to reproduce the problem
Break the Transport ring block and interact with the controller
## How often can you reproduce the issue?
- [ ] Always
- [x] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
Don't break them?
## What do you expect to happen instead?
For the controller to say it's not paired to any rings

**Comment by draksterau** [comment]
Just wow.

**Comment by draksterau** [comment]
shouldnt be an issue, Im invalidating rings at the point of requesting them.
