### ISSUE TITLE
Bug - Breaking Transport Rings doesn't always give back the block

### ISSUE THREAD

**Issue by CaptainNikolaus** [StargateMC/IssueTracker#339]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v1.3.5

## Did you receive an error message? If so, copy it here.
Nope

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [x] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes
- [ ] No

## What would you describe the problem as?
Breaking the Transport Ring Block doesn't always drop the block, losing a tedious item to craft and sometimes stranding someone on a planet/station

## Steps to reproduce the problem
Try breaking a Transport Ring Block

## How often can you reproduce the issue?
- [ ] Always
- [x] Most of the time
- [x] Some of the time
- [x] Rarely

## Can you work around the issue and continue playing?
- [x] No
- [x] Yes

## How to work around the issue
By not breaking it, but if you need to move it your stuffed

## What do you expect to happen instead?
For the Block to drop

**Comment by draksterau** [comment]
Ive tried  this and cant reproduce anymore. Initially when we updated, the block didn't drop.
