### ISSUE TITLE
Bug - Cannot craft empty cells, recipe clashes with Thermal Ex tin gears.

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#340]
## Version of the StargateMC Client
v3.2.2

## Did you receive an error message? If so, copy it here.
Not applicable.

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## Detail what you have modified in the client here, if applicable
Not applicable.

## What would you describe the problem as?
Some recipes from IndustrialCraft 2 Classic clash with recipes of Thermal Expansion and other mods. One such recipe is for making empty cells required to make some machines/items.

## Steps to reproduce the problem
1) Obtain Tin ore and process it into ingots.
2) Attempt to craft empty cell as shown in JEI in any crafting table.
3) Item output shows as tin gear instead of empty cell x16

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [ ] Yes
- [x] No

## How to work around the issue
Would require a modified recipe using crafttweaker to allow empty cells to be crafted normally.
A suggested recipe could be 4 tin ingots around 1 glass block/pane in a crafting grid. Or tweaking gear recipe to compensate for this.

## What do you expect to happen instead?
Expected output is empty cells x16 from 4 tin ingots in the arrangement shown in JEI.

**Comment by Joey4213** [comment]
fixed
