### ISSUE TITLE
Bug - Mekanism Doesnt implement the IC2 API properly, has incompatibility with IC2 Classic

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/IssueTracker#341]
`[10:31:40] [Server thread/WARN] [ic2]: API ERROR: mekanism.common.tile.TileEntityInductionPort@6e64b4a6 didn't implement demandsEnergy() properly, no energy from injectEnergy accepted although demandsEnergy() returned true.
`

**Comment by Nerion1** [comment]
Works as intended. Closed.
