### ISSUE TITLE
Bug - Aunis TR - Unable to reach an address with number 0

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#343]
Aunis rings work only on numbers 1-6. and ring names are not correct. i was able to reach a ring with a wrong number

0. P2X3YZ0PL
1. P2X3YZ1PL

if i'm on YZ1 and click 1 i go to earth

**Comment by luckyrada** [comment]
It says 0 but if you click the first button on ring controller it transports you to the rings with the address 0

**Comment by TheRedCreations** [comment]
The Number issue has been fixed
