### ISSUE TITLE
Suggestion - MoCreatures Modpack

### ISSUE THREAD

**Issue by Tappentine** [StargateMC/IssueTracker#344]
## What is your suggestion?
Ever since we had updated the server, we can have more mobs, it might be time to add a mod such as MoCreatures

>Why is this important?
This will add more diversity to more worlds, hopefully making players want to explore more, maybe capture animals

## How will this benefit players?
Gives players more reasons to travel, some galaxies may have different animals so will need to explore between galaxies via ships/stargates

>Why is this important?
Having living worlds will make more planets more fun to explore

## How will this change for players?
I don't see any initial issues with this apart from potential TPS, but this shouldn't cause any problems or changes to the players life on the server

>Why is this important?
This is important as its a positive addition to the server, for players and the server as a whole which shouldn't conflict with any current server features

## Do you consider this suggestion a:

- [] Must (Important to keep players happy)
- [] Should (Beneficial to players, but can do without)
- [x] Could (Beneficial to players, there is no important reason to do it

>[Why is this important?
This is could as the server doesn't need this, but it could be an amazing addition to add more life, like seeing a herd of elephants once you go through a Stargate. The mod also includes creatures which aren't from Earth, such as Ogres (But I have a feeling these can be disabled if need be)

The mod link is -
http://www.9minecraft.net/mocreatures-mod/

I hope this could be considered for the server.

**Comment by Joey4213** [comment]
eh... I mean its a good idea on paper, but its not really fitting the theme of the server in my eyes, I cant speak for anyone else but that seems like its more of a real modded minecraft mod.

**Comment by ComputerCraft32** [comment]
Sounds like a good idea! Please note that 9minecraft mods often contain viruses. Only download from the official websites. It would make server more lively.

**Comment by Joey4213** [comment]
Im going to close this for the purpose of I dont believe we will be adding this because it wouldnt exactly be cannon for the modpack
