### ISSUE TITLE
Suggestion -  StargateBot Announcments

### ISSUE THREAD

**Issue by Tappentine** [StargateMC/IssueTracker#347]
## What is your suggestion?
Have the Stargate bot send DM's for important announcements 

>Why is this important?
Some people don't have all the time to read every message that comes on the live server, or doesn't have time to read every announcement. 

## How will this benefit players?
Gives them more warning privately do get them to understand that a change may affect them

>Why is this important?
This is important for instance of changes to the mod pack. For instance, when IC2 went back to classic, I didn't have the time to come online but didn't find much need to. If I knew this IC2 change happened, I would've adapted my station ready for the change.

## How will this change for players?
No real issues will occur, this will help with communication on the server overall. You might be able to do announcements for good things to the server as well if it includes the whole server .

>Why is this important?
Knowing potential and changes that may affect players will let them know that they are being brought into the loop of the server overall.

## Do you consider this suggestion a:

- [x] Must (Important to keep players happy)
- [] Should (Beneficial to players, but can do without)
- [] Could (Beneficial to players, there is no important reason to do it

>[Why is this important?
When you get a message that would read something like "There will be a change to the server that may affect you in the next 2 days, please make the necessary changes before this to avoid any issues"

With this sort of work, players will be able to see what is happening and shouldn't complain about anything that happens unexpectedly

**Comment by draksterau** [comment]
@Tappentine Eg: Ic2c. I totally support this.

**Comment by draksterau** [comment]
@Tappentine if you need a hand with your base after the ic2c move let us know :)

**Comment by Tappentine** [comment]
Cheers mate. Sorry bout the other day, I got really pissy about the whole situation, totally unprofessional. But I think that's sorted now (agentmaw did all the hard work) I'll be going on later to see what happens. Cheers though, ill see how it goes :)

**Comment by draksterau** [comment]
Added a /sg broadcastall cmd. Ill update the updater to broadcast changes shortly.

https://github.com/StargateMC/StargateMCMod/commit/aa896f7b421afd12f755142cee9bedb459438356

**Comment by Bysokar** [comment]
This is done - will be enabled with the next live update.
