### ISSUE TITLE
Suggestion - Towny Settlements

### ISSUE THREAD

**Issue by Tappentine** [StargateMC/IssueTracker#348]
#298  What is your suggestion?
We add a plugin similar to or same as Towny

>Why is this important?
Players can have obvious wars between factions on the server, and alliances and nations

## How will this benefit players?
Allow alliances to be formed through the server rather than through discord, help to make settlements and towns instead of just spanning everywhere.

>Why is this important?
Alliances are a main part of Stargate, as I can see from the server, it is being looked into, but potentially, making it easier for players to start factions and towns could aid in making allies and/or enemies overall

## How will this change for players?
This will make interactions easier, you can see what faction a person is apart of, and act accordingly. This might make people start using flags or banners to symbolize their areas. This could also be having home planets for nations to reside where they know they can be safe (Of course, this is the players decision)

>Why is this important?
This will change the dynamic of making allies and enemies on the server, and caring about making friendships and taking land to further their own empire.

## Do you consider this suggestion a:

- [] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [] Could (Beneficial to players, there is no important reason to do it

>[Why is this important?
I feel to assist in the server's war dynamic that this should be implemented as a possible feature to help people.

https://www.spigotmc.org/resources/towny-advanced.72694/

**Comment by draksterau** [comment]
Hi @Tappentine,

We will be implementing a clan / faction style setup which allows players to create private communications channels etc.
We won't be allowing claims though.

As for the relationship players have with eachother, we're gearing up to having players pick a side in the Stargate universe, focused around NPC driven factions.

This means we'll have players who are friendly with the tauri forced into a situation where they cant really befriend a Goauld-allied player and vice versa without some degree of difficulty.

That sound alright with you? 

Cheers,

Byso
