### ISSUE TITLE
Suggestion - add the mod NoMoreRecipeConflict

### ISSUE THREAD

**Issue by deathbewithyou** [StargateMC/IssueTracker#350]
[Please fill out the form below and delete the sections in square brackets after reading them]

## What is your suggestion?
>Add the mod NoMoreRecipeConflict

## How will this benefit players?
>Prevents the possibility of an item being uncraftable due to recipe conflicts

## How will this change for players?
>Adds a toggle in the crafting UI that allows players to cycle through possibles items crafted by the recipe

>Why is this important?
>To allow players to progress when a conflict arises 

## Do you consider this suggestion a:

- [x] Must (Important to keep players happy)
-  Should (Beneficial to players, but can do without)
-  Could (Beneficial to players, there is no important reason to do it

>[Why is this important?
>Knowing if the request is something you consdier a deal break or not is important!]

**Comment by CaptainNikolaus** [comment]
Nah not needed, just report conflicting recipes when they pop up
