### ISSUE TITLE
Bug - Slimeball recipe

### ISSUE THREAD

**Issue by Mace-Windu1** [StargateMC/IssueTracker#351]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
> 3.4.0

## Did you receive an error message? If so, copy it here.
> No

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] No

## Detail what you have modified in the client here, if applicable
> N/A

## What would you describe the problem as?
> One of the slimeball recipes is broken. The mud ball and green dye recipe is broken and does not produce anything.

## Steps to reproduce the problem
> Try to use the slimeball recipe that uses mud balls and green dye.

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
> Use the other recipe

## What do you expect to happen instead?
> Produce 4 slimeballs instead of nothing

**Comment by Joey4213** [comment]
Ah fuck, that one is all mucked up too?

I will fix it tonight when I get on

**Comment by NovaLynxie** [comment]
There was another recipe that was bugged too. Mainly due to recipe clashing. #354 includes this information.

**Comment by Joey4213** [comment]
pushing right now :D
