### ISSUE TITLE
Bug - Some recipes are still broken. (Slime ball, IC2C Empty Cells, etc.)

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#354]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v3.6.3 (Client at time of posting)

## Did you receive an error message? If so, copy it here.
No error messages thrown.

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automatically into the Technic Launcher?
- [ ] Yes
- [x] No

## Detail what you have modified in the client here, if applicable
No changes made.

## What would you describe the problem as?
Recipes such as Slime balls and Empty Cells which either make or use IC2 Classic items do not work correctly.
Empty Cells require 4 tin ingots **same as tin gears** which overrides this. Meaning we cannot make the cells to make some of the necessary machines in IC2 Classic.
Slime ball recipes use the plant balls, this was broken after the mod change from IC2 Experimental to IC2 Classic
This makes it impossible to make slime balls needed for many different recipes, such as sticky pistons, parts for machines and many more.

## Steps to reproduce the problem

1. Make a vanilla crafting bench or any equivalent from AE2, IC2, etc.
2. Lay out the items as shown in the recipes from JEI.
3. Once the recipe is formed it should produce an output in the right hand square output.

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [x] No
Yes and No (See How to work around the issue)

## How to work around the issue
Empty cells yes, by making coolant cells, it will drop the empty cells as a byproduct.
Slimeballs on the other hand not so much. Farming aquaculture squid (fish item) would be next to impossible making this very tedious and slow going.

## What do you expect to happen instead?
The recipes should have made their respective items but cannot due to either missing items or clashing recipes.
Slimeballs should be made using Mud ball x4, Cactus green (or green dye) x4 and 1 Plant ball.
Empty Cells recipe clashes and therefore would still be uncraftable unless a workaround is found.

**Comment by Joey4213** [comment]
Thank you for putting the time in to make a github issue about the issues, am aware of all the currently known issues, they will be fixed soon
#349 #351
