### ISSUE TITLE
Bug - Advanced Rocketry Orbital Laser Drill deleting lens block inside it

### ISSUE THREAD

**Issue by CaptainNikolaus** [StargateMC/IssueTracker#355]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
V3.6.4

## Did you receive an error message? If so, copy it here.
Nope

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [x] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## What would you describe the problem as?
When using the Orbital Laser Drill, the multi-block structure and un render, but be invisible apart from the control block, which when interacted with will reform the structure and have removed the lens blocks in it
## Steps to reproduce the problem
Let a orbital laser drill run for a minute or two, and check on it 
## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
Mine manually on the planet, but this is easier

## What do you expect to happen instead?
For it to not "delete" my lens block

**Comment by Joey4213** [comment]
Yea, I have the same issue, it runs as normal but after some time the lens get deleted

**Comment by draksterau** [comment]
@Joey4213 This will likely occur if the coremod force-unloads a world. We may just want to stop it actually mining the blocks on the planet....

**Comment by CaptainNikolaus** [comment]
Due to the CoreMod force unloading worlds that the laser is mining on, can do what @draksterau says above, but will need to specify ores and blocks it could/can mine

**Comment by Joey4213** [comment]
This isnt fixed yet, we use github as a project board so this should stay open until fixed.

**Comment by draksterau** [comment]
@Joey4213

**Comment by draksterau** [comment]
@Joey4213 https://github.com/StargateMC/StargateMC/commit/1a206bb26bb302ddf6cf7744a05c744fbc6cd9ad
