### ISSUE TITLE
Bug - Transporter Ring Remote can't dial between each other

### ISSUE THREAD

**Issue by CaptainNikolaus** [StargateMC/IssueTracker#356]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v3.6.4

## Did you receive an error message? If so, copy it here.
When trying to dial ring 1 from 0 it says "Ring cant transport to themselves", and when trying 0 from 0 it says "Unable to reach this address"
This only happens some of the time, sometimes it will let you transport to one ring from the other, but can't return to the original

## Where are you playing?
- [x] Single Player
- [x] MultiPlayer (StargateMC.com)
- [x] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## What would you describe the problem as?
Can't use the Ring Transporter Remote, so have to rely on the Control panels, which add an extra cost to the construction of ring platforms

## Steps to reproduce the problem
Set up two Transport Rings, each on seperate planets/stations in the same system, and attempt to dial to the other using the remote

## How often can you reproduce the issue?
- [ ] Always
- [x] Most of the time
- [ ] Some of the time
- [ ] Rarely

>[Why is this important?
>Knowing how often the bug occurs for you is important for prioritisation of the team's time.]

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
Use block Transport Ring Controllers

## What do you expect to happen instead?
To be able to dial Transport Rings using the remote without issue

**Comment by TheRedCreations** [comment]
Number issue is fixed. will be available in next update
