### ISSUE TITLE
Chisel: No OpenGL context found in the current thread.

### ISSUE THREAD

**Issue by connerfick** [StargateMC/IssueTracker#358]
I am not exactly sure what is going on here, but here's the crash log,

[crash-2020-07-27_11.44.25-server.txt](https://github.com/StargateMC/IssueTracker/files/4983310/crash-2020-07-27_11.44.25-server.txt)

**Comment by TheRedCreations** [comment]
This wasn't chisel. It was SGCraft. it made an Correlative Update

**Comment by connerfick** [comment]
so how do I prevent it from crashing when it does that?

**Comment by TheRedCreations** [comment]
i don't know. The feature is really new.

**Comment by connerfick** [comment]
Does it help, that I have never built a stargate in the world.

**Comment by Joey4213** [comment]
i need to ask, this was in single player i assume?

**Comment by connerfick** [comment]
Yes it was singleplayer

**Comment by Joey4213** [comment]
theres the issue... the current build of sgcraft isnt built to handle singleplayer, if you want to play in single player you need to remove the sgcraft mod, otherwise just play on the server, just about anyone would be willing to answer a couple questions you have if any
