### ISSUE TITLE
Suggestion - Inventory Wipe on Unstuck Command

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#360]
## What is your suggestion?
>When someone preforms the Unstuck command their inventory should be wiped.

## How will this benefit players?
>Players will not have to worry about other players abusing this command for say raiding ones base for example.

## How will this change for players?
> Players will now not be able to use this command for easy transport around the galaxy and rather only use it as a last resort.

## Do you consider this suggestion a:

- [x] Must (Important to keep players happy)
- [ ] Should (Beneficial to players, but can do without)
- [ ]Could (Beneficial to players, there is no important reason to do it

**Comment by draksterau** [comment]
Good idea. I'll also add a cooldown.

**Comment by draksterau** [comment]
V3.7.6 adds a cooldown of 1 hour and clears inventories.
