### ISSUE TITLE
Bug - MFFS forcefield Items aren't craftable

### ISSUE THREAD

**Issue by Alkear** [StargateMC/IssueTracker#361]
## Version of the StargateMC Client
>

## Did you receive an error message? If so, copy it here.
>

## Where are you playing?
>MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
>No

## Detail what you have modified in the client here, if applicable
>

## What would you describe the problem as?
> the crafting recipe for modular forcefield system’s projector upgrade is missing a component (was in IC2)

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Not build a forcefield system

## What do you expect to happen instead?
>the item uses components that are in game

**Comment by Joey4213** [comment]
fixing right now and then pushing :D
