### ISSUE TITLE
Bug - some gates wont shut down after dialing another address 

### ISSUE THREAD

**Issue by PIkachu0111** [StargateMC/IssueTracker#362]
## Version of the StargateMC Client
v3.7.2

## Where are you playing?
- [ ] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## What would you describe the problem as?
when you dial from some stargates the connection dont get terrminated after 38 second either when you stay on the planet or when you step through. there are two planets that i know of having this issue ,dont want to meantion the address here.(one one of them i tested workeround 2)

## Steps to reproduce the problem
go on the planet and dial another planet and either stay on that planet or go through. 

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
1.when already stepped through another player can repeatedly try dial the gate at some point the connection is terminated
2.when still on the planet than simply disconnect the stargate and break and place the stargate base block. 
the second workaround solves the issue permantly

## What do you expect to happen instead?
that it close after the normal open time.

**Comment by draksterau** [comment]
Fixed in v3.7.7
