### ISSUE TITLE
Linux JRE doesn't recognize MaxPermSize option.

### ISSUE THREAD

**Issue by connerfick** [StargateMC/IssueTracker#363]
This is the error that I am getting.

The game is running. Please wait.
Unrecognized VM option 'MaxPermSize=256M'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Process ended with code: 1

**Comment by draksterau** [comment]
@connerfick Looks like Java 9 removes support for PermGen. Ill release a Launcher update today for this one :) 
Thanks for reporting :)

**Comment by draksterau** [comment]
@connerfick v1.0.6 of the StargateMC launcher has been released. This no longer uses PermGen, as it is unsupported.

Please let me know by responding to this if you have any issues with the new version.
