### ISSUE TITLE
Suggestion - Compact Machines

### ISSUE THREAD

**Issue by RicoPeav** [StargateMC/IssueTracker#367]
[Please fill out the form below and delete the sections in square brackets after reading them]

## What is your suggestion?
> This mod would add a block that you can shrink into, capable of expanding to 11x11. https://www.curseforge.com/minecraft/mc-mods/compact-machines

## How will this benefit players?
> It could be used as an on the move base, used to ease construction in tight spaces, and simply as a storage unit. 

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [ ] Could (Beneficial to players, there is no important reason to do it)

**Comment by Joey4213** [comment]
+1 would love to see this

**Comment by JayCoolGuy** [comment]
+1 Would be great to have this mod

**Comment by ComputerCraft32** [comment]
-1 Very bad mod. It would increase load times, and is not canon in any way.

**Comment by Joey4213** [comment]
actually im not so sure i think its all contained in one dimension so it would be similar to space

**Comment by BenFRC5147** [comment]
+1. All contained in 1 dim is true, and while they never explicitly dealt
with shrinking/enlarging, it's not out of the realm of possibility with the
other technologies we've seen. It would also allow for the creation of
custom multiblocks to get certain things, such as a multiblock Naquadah
Generator, or really anything that can output fluids,items, and or energy.
Could also probably be modified to create field technologies such as attero.

**Comment by RicoPeav** [comment]
All machine interiors are within one dimension, but each machine interior is only loaded when the machine exterior is loaded. So, it shouldn't cause any lag issues as long as people don't go full blown overboard.

**Comment by Joey4213** [comment]
so dont joey it up?

**Comment by JayCoolGuy** [comment]
Tbh it does remind me of the Spatial storage dimension

**Comment by RicoPeav** [comment]
nah, spatial storage is completely different.

**Comment by BenFRC5147** [comment]
In that all spatial cells are in different dimensions, and you are
extremely limited in what you can Pylon in and out of the cell

**Comment by draksterau** [comment]
This effectively is you guys asking me to re-enable Spatial storage.... which I'd consider trying to support before adding this mod.
Sorry but lag is already enough of an issue.

**Comment by draksterau** [comment]
Closing this as for the foreseeable future we will not be accepting any pocket dimension mods. Our dimension counts are high enough.
