### ISSUE TITLE
Suggestion - Add Engineer's Decor mod

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#370]
## What is your suggestion?
Engineer's Decor, a mod add-on for Immersive Engineering, adds some IE themed blocks, windows, support beams, decoration and some useful machines and utilities. It includes some logistic controls such as fluid valves for the pipes, small electric furnaces, an incinerator when you want to remove excess waste items automatically which I think is very cool looking,
Mod Link: https://www.curseforge.com/minecraft/mc-mods/engineers-decor (Has a 1.12.2 version in files, I've linked them below)
https://www.curseforge.com/minecraft/mc-mods/engineers-decor/files/all?filter-game-version=2020709689%3A6756

## How will this benefit players?
This gives more options for blocks and decorations which further utilize IE and would allow further customization as well as some early game machinery such as a small electric lab furnace, small waste incinerator, fluid control for IE pipes and more.
It would also complement the Engineer's Doors mod add-on in decorating and making fancy industrial factory builds.

## How will this change for players?
In some ways it helps provide other decoration blocks, adds some useful starter machinery for IE and some utilities that can be used to control fluid flow and manage conveyors. There is also a means to allow for multiple recipes in the modpack to work together and work around conflicts as this mod add-on's crafting tables can flip between recipes in its own crafting table built-in without the need of another mod to do it for you.

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [ ] Should (Beneficial to players, but can do without)
- [x] Could (Beneficial to players, there is no important reason to do it)

**Comment by TheRedCreations** [comment]
@Joey4213 this one is for you.

**Comment by Joey4213** [comment]
would need the ok from @draksterau to be able to add it, till i get that i will leave this as is but when we get the ok i shall test immediately

**Comment by CaptainNikolaus** [comment]
Can't do as i can't find a 1.12.2 version, if you can locate a download for it i'd be more than happy to reopen this

**Comment by CaptainNikolaus** [comment]
Nevermind, will test soon

**Comment by NovaLynxie** [comment]
Was about to say XD
Yeah curse forge has a habit of 'hiding' older versions and showing the newer versions first.

**Comment by CaptainNikolaus** [comment]
Been added

**Comment by Bysokar** [comment]
@CaptainNikolaus no it hasnt?
