### ISSUE TITLE
Bug - Unable to process Sticky Resin to Rubber via smelting with any furnace or extracting machines from IC2 Classic.

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#372]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v3.9.4

## Did you receive an error message? If so, copy it here.
No errors, just unable to smelt/extract any sticky resin.

## Where are you playing?
- [ ] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## Detail what you have modified in the client here, if applicable
Cannot make any rubber by smelting with a furnace, even vanilla furnaces or extracting in the extractor from IC2 Classic. This limits any power cable production to make insulated cables and is required to make circuits for machines.

## What would you describe the problem as?
I have tried multiple furnaces to smelt sticky resin into rubber and extractor machine but it either will not accept or the furnace/machine does not process it at all. It just remains in the input slot with no processing action.

## Steps to reproduce the problem
1) Craft any furnace or extractor machine.
2) Feed fuel or power into the machine either manually or cables/pipes.
3) Try to put the sticky resin into the furnace (Redstone Furnace refuses to accept it) or extractor and wait to see if progress bar goes up.

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
Unable to work around this issue so far as this is the only way to get rubber. 
Obtain sticky resin from fully grown rubber trees in the world using a tree tap or electric tree tap.

## What do you expect to happen instead?
When either furnace smelting or processing sticky resin in an extractor it should output rubber.
Furnace smelting produces 1:1 ratio while extractor produces more rubber per 1 sticky resin.

**Comment by CaptainNikolaus** [comment]
Code is waiting to be pushed by sokar

**Comment by NovaLynxie** [comment]
Updated the workaround area till this is a patch is pushed.

**Comment by CaptainNikolaus** [comment]
Will be added in next major update, use manual resin farms till then
