### ISSUE TITLE
Client Crash - Exception in thread "main" java.lang.ClassCastException:

### ISSUE THREAD

**Issue by connerfick** [StargateMC/IssueTracker#373]
when I try to launch the client, after logging in, the messages and errors page pops up but then I get this:

The game is running. Please wait.
Exception in thread "main" java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

**Comment by draksterau** [comment]
@connerfick Please post your Launcher version, Java Version and any custom config / mods you may have..

**Comment by connerfick** [comment]
Launcher: v1.0.6
Java: v1.8.0_261 Linux
Mods: and some of the stock launcher optional mods

**Comment by draksterau** [comment]
@connerfick That error cannot be coming from Java 8. Are you sure you dont have Java 10+ installed?

https://bugs.mojang.com/browse/MC-131315

Please make sure you only have 1 version of Java installed on the machine.

**Comment by connerfick** [comment]
That might be it. I'm using Java 8 for it but the computer has Java 9 installed in the system files.

**Comment by draksterau** [comment]
Can you try with only Java 8 (and then again with Java 9) installed please?

Make sure to restart before each test.

**Comment by connerfick** [comment]
No because I don't have admin privileges.

**Comment by draksterau** [comment]
Hmm okay. Well ill see what I can do.

**Comment by draksterau** [comment]
@JayCoolGuy @Joey4213 Want to see if you can reproduce please?
Id rather not put in code to support this scenario before i know the exact scenario.

**Comment by connerfick** [comment]
No I think I may need to specify which Java to use in the launcher itself the jvm path setting is empty. That might be what the issue is they can't decide which Java to use.

**Comment by draksterau** [comment]
@connerfick That would do it - try specifying: C:\Program Files\Java\jre1.8.0_261 (For example).

**Comment by draksterau** [comment]
@connerfick If that works I will try and pre-fill that field with the ideal Java version if multiple are installed.

**Comment by connerfick** [comment]
Actually it would not be C:\ Drive anything it's Linux

**Comment by draksterau** [comment]
yeah youll have to find the location then and use a unix file path :)

**Comment by connerfick** [comment]
Specifying the Java location caused it to work.
