### ISSUE TITLE
Bug - Enriched Sunnarium Alloy isn't craftble

### ISSUE THREAD

**Issue by PIkachu0111** [StargateMC/IssueTracker#374]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
v3.9.4

## Where are you playing?
- [ ] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## What would you describe the problem as?
When I put the enriched sunnarium and the sunnarium alloy in the pattern as jei showes it. the end product(Enriched Sunnarium Alloy) isnt showen in the output slot of the crafting table

## Steps to reproduce the problem
see What would you describe the problem

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [ ] Yes
- [x] No

## What do you expect to happen instead?
That i can craft the Enriched Sunnarium Alloy.

**Comment by CaptainNikolaus** [comment]
Recipe has been fixed, will be pushed on next Major Update - No Current Work Around
