### ISSUE TITLE
Client Crash - java: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.

### ISSUE THREAD

**Issue by connerfick** [StargateMC/IssueTracker#376]
[Stargate MC Error.txt](https://github.com/StargateMC/IssueTracker/files/5065100/Stargate.MC.Error.txt)
[StargateMCLauncher.txt](https://github.com/StargateMC/IssueTracker/files/5065216/StargateMCLauncher.txt); .sh file used to launch the game.

I'm not sure what type of error this is, the process ended with code 134. Then showed the launcher again.

Computer stats
Operating System: Ubuntu Mint 64bit
Java: jre1.8.0_261; installed In /home/(User)/StargateMC/jre1.8.0_261; no Sudo or Root Access
Ram: 16GB
Processor: AMD Athlon II X2 255 Dual Core 3.1GHz 
Video Card: NVIDIA GeForce GT 730

**Comment by Bysokar** [comment]
Noveau crashes are due to the driver your using for your video card (Nvidia) not working with Minecraft. This is nothing to do with StargateMC.

Try using Nvidia's proprietary linux drivers.
