### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by QuintOliveira** [StargateMC/IssueTracker#377]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>3.9.4(Live)

>Why is this important?
>Knowing the version of StargateMC helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Where are you playing?
- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] No

## What would you describe the problem as?
>When I went to make pipe sealant in the compressor using sticky resin, the compressor did not accept to put the resin

## Steps to reproduce the problem
> First i try to put sticky resin in the compress, but the compressor don´t accept

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] Yes

## How to work around the issue
>Using in the crafting table cactus, then we have the pipe sealant

**Comment by Bysokar** [comment]
@CaptainNikolaus Please confirm if this is resolved in test already.

**Comment by Bysokar** [comment]
This is fixed on test and will be provided in the next live update.
