### ISSUE TITLE
Client Crash - Launcher, failed to find launchable .jar

### ISSUE THREAD

**Issue by Byyk** [StargateMC/IssueTracker#380]
# Version of the StargateMC Client
>1.0.6

## Can you find your crash on OpenEye (https://openeye.openmods.info/crashes)?
- [ ] Yes
- [x] No

## Link to Crash Report (OpenEye or Pastebin)
>https://pastebin.pl/view/23981ad7

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## Steps to reproduce the crash
> Don't know why this happen, but I had to install Java JDK in order to see the exception.

## How often can you reproduce the crash?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you continue playing after the crash occurs and you re-load the client?
- [ ] Yes
- [x] No

## How to work around the issue
> No, it's an exception only dev can fix this problem

## What do you expect to happen instead?
> I expect it to open the launcher.

**Comment by Bysokar** [comment]
Please list the below and I will try and help.... as previously mentioned I'm happy to use teamviewer or a similar service to help diagnose the problem for you.

1. All versions of Java installed.
2. Your operating system version.
3. If you have administrative rights to your machine.
@Byyk 

This issue is not to do with the launcher, its something wrong with how your computer is configured, or the user you are trying to run the launcher as doesnt have rights to its My Documents folder.

**Comment by Byyk** [comment]
Thanks for quick answer.

1. jdk 11.0.4, jdk 14.0.2 and jre 1.8.0_261. See my Java folder https://ctrlv.cz/FXz6
2. Windows 10 Home, Version: 1909, OS build: 18363.1016
3. Yes, I have Administrative right to my PC

**Comment by Bysokar** [comment]
Hi @Byyk,

I recommend you uninstall the 2 JDK versions and replace them with JDK 1.8.0 Update 261 from Oracle - that matches your JRE - its jdk-8u261-windows-x64.exe here: https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
JDK 10 and 11 have known issues with Minecraft v1.12, let alone our launcher and having multiple installed at once can confuse things....

If you cant uninstall the multiple versions of java, you can use the .Jar launcher and run it from command line, targetting JRE 1.8 u261.
If you can get the Launcher to open, You can define a JVM path to specify which also.

Regards,

Bysokar

**Comment by Byyk** [comment]
That's a lot that worked.
