### ISSUE TITLE
Suggestion - Disable Varied Commodities steel making recipe.

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#382]
## What is your suggestion?
Remove or disable this recipe that makes Varied Commodities steel as this makes a much easier way to produce steel and will bypass any existing methods by Immersive, Mekanism, Thermal or IC2 as this requires quite literally a simple furnace, fuel and iron ingots. This would make players work for their steel ingots rather than make it very easily and as such bypass other means of steel production from other mods making their recipes or methods completely obsolete due to how easy it is.

## How will this benefit players?
Not really a benefit as such. (See 'How will this change for players?')

## How will this change for players?
By removing this method, players will have to work towards making their steel instead of being lazy and making mass amounts of it with ease.

## Do you consider this suggestion a:

- [x] Must (Important to keep players happy)
- [ ] Should (Beneficial to players, but can do without)
- [ ] Could (Beneficial to players, there is no important reason to do it

Not sure about the happy part, but would definitely be important to maintain usage of existing recipes for steel from other mods.

**Comment by CaptainNikolaus** [comment]
Recipe has been fixed and will be pushed sometime in the next week

**Comment by CaptainNikolaus** [comment]
Issue solved as of v4.0.6.8
