### ISSUE TITLE
Bug - Missing NPC's

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#383]
No NPC's at SGC.
All users get stuck there.
PDD dial not working.

**Comment by Bysokar** [comment]
whaaa

**Comment by TheRedCreations** [comment]
![2020-08-25_15 59 02](https://user-images.githubusercontent.com/35812887/91183600-f4fac680-e6eb-11ea-9cf9-99ee45085ad5.png)

**Comment by TheRedCreations** [comment]
and something invisible hits me on floor 27 near elevator

**Comment by Bysokar** [comment]
@TheRedCreations I think the client side update to CustomNPCs failed. Ill revert.

**Comment by TheRedCreations** [comment]
ok

**Comment by TheRedCreations** [comment]
you can update without countdown

**Comment by Bysokar** [comment]
Resolved for now :)
