### ISSUE TITLE
Bug - cant play the game

### ISSUE THREAD

**Issue by spiceweasel420** [StargateMC/IssueTracker#385]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>4,0,7.9

>Why is this important?
>Knowing the version of StargateMC helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Did you receive an error message? If so, copy it here.
>game says java isnt responding whenever i load in

>Why is this important?
>Knowing the exact wording of an error allows us to scan hundreds of thousands of lines of code and configuration files quickly to identify where the problem occured ]

## Where are you playing?
- [x] 
- [x]mult
- [x] 

>[Why is this important?
>We need to know what you're doing and where, as there may be server side information or code that only fires in single player that needs to be reviewed as well.
>Be aware that we may not support all features in Single Player and do not support connecting to other servers from the StargateMC client.]

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] 
- [x] No

>[Why is this important?
>We need to know if you're changing the client to help identify if that is related to the issue. 
> Running client mods is fine, but we will not necessarily provide support to you if you run them and they cause issues!]

## Detail what you have modified in the client here, if applicable
>none

>Why is this important?
>Detailing what mods or custom configurations you are running in addition to the official pack helps us troubleshoot things faster, as well as pick up on popular client side mods that we may want to pull into the official build.]

## What would you describe the problem as?
>whenever i load in , my game runs at 0 frames per second and i cant move , but i can see the live chat update as people talk . graphics card runs at 0% usage aswell

>Why is this important?
>Knowing what you consider broken is important - we may or may not agree with you]

## Steps to reproduce the problem
> literally logging in

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]
i cant play the game at all 
## How often can you reproduce the issue?
- [x] Always

>[Why is this important?
>Knowing how often the bug occurs for you is important for prioritisation of the team's time.]
cant play without this fixed
## Can you work around the issue and continue playing?
- [x] No

>[Why is this important?
>Knowing if the issue can be worked around will help with prioritsation of the team's time, as well as other players while we fix it!] 

## How to work around the issue
>[If you can, decribe how you work around the issue here to continue playing.
i cannot

>Why is this important?
>Including a known workaround in the issue helps people reviewing issues before reporting continue playing once they come across yours!]

## What do you expect to happen instead?
>[id like to play the game please <3 

>Why is this important?
> because i love the server

**Comment by Nerion1** [comment]
Spice advised this issue was caused due to a massive amount of cobblestone being spawned on their ship which made it impossible to log in. The issue has since been resolved and the cobblestone cleared.
