### ISSUE TITLE
Bug - Pre generated Ringplatform does not generate

### ISSUE THREAD

**Issue by TheRedCreations** [StargateMC/IssueTracker#387]
I traveled to a ringplatform(from space to a planet pre gen ring). i appeared at the ring coords but there was no ring.
![2020-09-02_20 23 32](https://user-images.githubusercontent.com/35812887/92021524-30d00480-ed5a-11ea-8c1a-f049d55408f6.png)

**Comment by TheRedCreations** [comment]
ok. i checked it again. it transported me to the wrong coords

**Comment by Bysokar** [comment]
Is this still an issue @TheRedCreations ?

**Comment by TheRedCreations** [comment]
Have to check. I wasn't on with latest version

**Comment by TheRedCreations** [comment]
Still issue. The Rings put me not to destination coords.

**Comment by TheRedCreations** [comment]
Pre gen Rings are now generating. -> closed
