### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by Lonestargazer** [StargateMC/IssueTracker#390]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
Latest

## Did you receive an error message? If so, copy it here.
>[insert here

## Where are you playing?

- [x] MultiPlayer (StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [x] Yes

## Detail what you have modified in the client here, if applicable
>[nothing

## What would you describe the problem as?
>[I died and i respawned on OJ5A-MK0-OL and the dialling Npc isn't here or its maybe underground.

## Steps to reproduce the problem
>[Go on OJ5A-MK0-OL

## How often can you reproduce the issue?
- [x] Always

## Can you work around the issue and continue playing?
- [x] No

## How to work around the issue
>[spawn NPC on the surface

## What do you expect to happen instead?
>[Spawning NPC on ground

**Comment by Nerion1** [comment]
This location has been removed until completed.
Closed.
