### ISSUE TITLE
Suggestion - I have serious lags when playing on the live server 

### ISSUE THREAD

**Issue by 0NDINEK** [StargateMC/IssueTracker#392]
[Please fill out the form below and delete the sections in square brackets after reading them]

## What is your suggestion?
>it takes me +- minute to open chest or whatever machine ingame

>Why is this important?
>Knowing what you consider broken is important - we may or may not agree with you]

>Why is this important?
>it's unplayeable for me ;(

**Comment by Nerion1** [comment]
Hi 0NDINEK, 

Some fixes have been applied and have resolved performance issues for players. Could you please let me know if this is now resolved for you?

**Comment by Bysokar** [comment]
Resolved by clearing audit logs. Backlog item added to prune this file.
