### ISSUE TITLE
Bug - Corrupted Player Data

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#394]
So for reasons I cannot remember, about one week ago, I joined the live server, and I timed it out.  It required a restart for it to be able to function properly again.  The next times I have tried to join the server, the results were the same.  I believe that my player data is corrupted.  
I believe a simple player data wipe should be sufficient in fixing this problem.  Thanks.

**Comment by Nerion1** [comment]
Player data has been wiped and problem resolved.
