### ISSUE TITLE
Bug - Unfinished Spawn Location

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#395]
I am currently trapped in an unfinished spawn location. Specifically, the wraith hive ship.  There are no dialer npcs nor is there a dhd.  I cannot use the unstuck command to escape, because it is on cooldown since I had to use it earlier.  So I am trapped.  I recommend that this spawn location is cut off from players or completed.  I request help in escaping.

**Comment by Nerion1** [comment]
Have teleported Jay to SGC and will be removing unfinished spawns from lists so unstuck no longer sends you there later tonight.

**Comment by mainesi** [comment]
Thanks Nerion for that, however, that spawn did have NPC's originally so am not sure what has happened there. This seems to be more of a NPC issue or a bug in dimension loading

**Comment by Bysokar** [comment]
I have removed all references to spawn locations that aren't polished enough  to use.
Players will no longer land there when they die.
