### ISSUE TITLE
server freeze when i join no fix might need a reset or something

### ISSUE THREAD

**Issue by mrdotrun21** [StargateMC/IssueTracker#397]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of the StargateMC Client
>newest

## What time did this crash last occur for you? (Provide timezone as well!)
>well every time i log in

## What impact did this have on your client?
>none

>Why is this important?
>causes server to freeze not allowing anyone on

## Did you receive an error message? If so, copy it here.
>none server just stops working so it cant even create a log

>Why is this important?
>stops people playing

## Steps to reproduce the crash
>cant be stopped

## How often can you reproduce the issue?
- [x] Always

Does the server return to a healthy state afterwards?
- [x] Mostly, the server does restart if you force it or wait a long time and all players except me can login or the problem starts again

## How to work around the issue to prevent a server crash
>if i give sokar suck maybe ?? UwU

**Comment by Nerion1** [comment]
Live server functioning normally. Advise if issue persisting please.
Closed.
