### ISSUE TITLE
Server Crash - "

### ISSUE THREAD

**Issue by 0NDINEK** [StargateMC/IssueTracker#398]
## Version of the StargateMC Client
newest

## What time did this crash last occur for you? (Provide timezone as well!)
since 18:30 CEST

## What impact did this have on your client?
noone can play on server since its timing out everyone 

I gave traildog personal teleporter and I forgot to tell him not to use interdimensional ;-; I guess it broke the server

its importatnt bcs it broke the server

## Steps to reproduce the crash
Idk how to fix thus but I think it is really bad when noone can login ;-;

## How often can you reproduce the issue?
- [x] Always

## Does the server return to a healthy state afterwards?
- [x] No,the server starts and times everyone out repeatedly 

## How to work around the issue to prevent a server crash
idk

**Comment by Nerion1** [comment]
This item will be disabled as it is not needed.
Added to To Do List.
Closed.
