### ISSUE TITLE
Wooden storage crates disappear

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/IssueTracker#41]
When placing wooden storage create from immersive engineering while sneaking the crate will disappear then for .5 sec appear like a block update, the vanish.

Found out on the 01/31/2020 1 am MST in the US.

**Comment by Biomech434** [comment]
However, reappear upon login.

**Comment by StargateMC** [comment]
Weird, this might be the protection module in the coremod. Ill try and reproduce. Thanks @Biomech434 :)
