### ISSUE TITLE
Mod Suggestions for 1.12 Test Server

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/IssueTracker#45]
Here is a list of a few mods to add to the 1.12 pack.

- RPG Skills https://www.curseforge.com/minecraft/mc-mods/simple-rpg-skills

- Cat Walks  https://www.curseforge.com/minecraft/mc-mods/catwalks-4/files

- Effortless Building https://www.curseforge.com/minecraft/mc-mods/effortless-building/files

- Platforms https://www.curseforge.com/minecraft/mc-mods/platforms/files

1.Dependence Mod for Platforms "ShetiPhianCore" https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files 

**Immersive Engineering:**

- Immersive Petrolium https://www.curseforge.com/minecraft/mc-mods/industrial-wires

- Immersive Technology https://www.curseforge.com/minecraft/mc-mods/immersive-technology

- Industrial Wires https://www.curseforge.com/minecraft/mc-mods/industrial-wires

- Engineers Doors  https://www.curseforge.com/minecraft/mc-mods/engineers-doors

- Alternating Flux https://www.curseforge.com/minecraft/mc-mods/alternating-flux

- Immersive Engineering Tweaks  https://www.curseforge.com/minecraft/mc-mods/immersive-engineering-tweaks

- Immersive Energy https://www.curseforge.com/minecraft/mc-mods/immersive-energy

- Immersive Cables https://www.curseforge.com/minecraft/mc-mods/immersive-cables/files

**Applied Energistics:**

- AE2 Stuff https://www.curseforge.com/minecraft/mc-mods/ae2-stuff/files

- UniDict https://www.curseforge.com/minecraft/mc-mods/unidict/files

- Extra Cells 2 https://www.curseforge.com/minecraft/mc-mods/extracells2/files

- Wireless Crafting Terminal https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal/files

- Just Enough Energistics https://www.curseforge.com/minecraft/mc-mods/just-enough-energistics-jee/files

**Performance Mods:**

- DynIMC http://mc.lunatri.us/doc/legacy/dynimc/

- InGame Info XML  http://mc.lunatri.us/doc/legacy/igi/

- Monster Spawn Highlighter http://mc.lunatri.us/doc/legacy/msh/

- Schematica http://mc.lunatri.us/doc/legacy/schematica/

- Stackie  http://mc.lunatri.us/doc/legacy/stackie/

- Lag Goggles https://www.curseforge.com/minecraft/mc-mods/laggoggles/files

I'll add to this list as I Think of more to add.

**Comment by StargateMC** [comment]
Immersive we can do. RPG skills not so much :)

**Comment by StargateMC** [comment]
Added Some of the immersives, as well as AE2 Stuff and Engineers doors. The rest I am not comfortable adding at the moment. Some of them havent been updated in a while & I cant access source code to fix crash bugs.
