### ISSUE TITLE
Stargates need to spawn during world generation & on demand

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#56]

**Comment by Biomech434** [comment]
Are their other ruins that the gates can generate with, compared to the last gate gen mechanic?

**Comment by StargateMC** [comment]
@Biomech434 What do you mean other ruins? :) 
There are 100% customisable structures now!!! Ill explain it later =D

**Comment by Biomech434** [comment]
That was before I found out about the mod you found.
