### ISSUE TITLE
Gate Mechanics

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/IssueTracker#58]
While dialing out, if there is a "strong gravitational force in the system", the gate will not dial out or receive a wormhole request. If I remember this intended, but, have a way to let the player know or determine what systems will have this issue beforehand, or have a way for players, to bypass that mechanic. i.E say with an extream amount of power, or a certain shielding on the gate or a multiblock structure/advanced gate buffer attachment, to allow dialing with the gravity interference.

**Comment by StargateMC** [comment]
At this stage, gates can only dial to/from other blackhole systems. They dial without any player provided energy cost.... so the 'downside' is an inability to dial into the system from another location.
I'll rework this once things settle down.
