### ISSUE TITLE
Gate Location

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/IssueTracker#59]
While On a planet, some way to locate the gate on the planet, unless it is a gate that has a "location shielding upgrade" on it.

**Comment by Biomech434** [comment]
I was thinking about how you could do that. AR has a mechanic with a multi block structure that is a sort of beacon. Maybe see about reusing that mechanic for this. Instead of a helm to sense the direction it puts it on the mini map like a global coordinate for that dim.

**Comment by StargateMC** [comment]
I'm going to use the AR satellite system to do this if possible :)
